export const billboardData = [
    {   
        id: "qwert12345",
        name: 'Ketu02',
        location: 'Along Enugu airport road, by Engineering department facing the terminal, Emene',
        type: 'led',
        height: '12',
        width: '20',
        status: 'active',
        category: 'billboard',
        class: 'digital',
        faces: '1',
        slots: '1',
        units: '1',
        region: 'southwest',
        state: 'lagos',
        lga: 'ikeja',
        city: 'maryland',
        coordinate: '8.524242,8.123456',
        amount: '300,000,000'
    },
    {
        id: "yuio6789",
        name: 'Tiger',
        location: 'Apongbon ftt outer marina',
        type: 'lightbox',
        height: '12',
        width: '20',
        status: 'active',
        category: 'billboard',
        class: 'digital',
        faces: '1',
        slots: '1',
        units: '1',
        region: 'southwest',
        state: 'lagos',
        lga: 'ikeja',
        city: 'maryland',
        coordinate: '8.524242,8.123456',
        amount: '300,000,000'
    },
    {
        id: "opasd101112",
        name: 'Lion',
        location: 'Apongbon ftt outer marina',
        type: 'rooftop',
        height: '12',
        width: '20',
        status: 'active',
        category: 'billboard',
        class: 'digital',
        faces: '1',
        slots: '1',
        units: '1',
        region: 'southwest',
        state: 'lagos',
        lga: 'ikeja',
        city: 'maryland',
        coordinate: '8.524242,8.123456',
        amount: '300,000,000'
    },
    {
        id: "zxcvb14416",
        name: 'Rhino',
        location: 'Apongbon ftt outer marina',
        type: 'eye-catcher',
        height: '12',
        width: '20',
        status: 'active',
        category: 'billboard',
        class: 'digital',
        faces: '1',
        slots: '1',
        units: '1',
        region: 'southwest',
        state: 'lagos',
        lga: 'ikeja',
        city: 'maryland',
        coordinate: '8.524242,8.123456',
        amount: '300,000,000'
    }
];