const getStateLga = (state) => stateData[state];

const getLgaCity = (lga) => cityData[lga];

const stateData = {
  northcentral: {
    benue: [
      { lga: 'Agatu', cities: ['Obagaji', 'Obaji'] },
      {
        lga: 'Apa',
        cities: [
          'Ugbokpo',
          'Iga',
          'Akpete',
          'Oiji',
          'Ojope',
          'Igoro',
          'Ochekwu',
          'Edikwu',
          'Achaba',
          'Ahija',
          'Adija',
          'Amoke',
          'Akpanta',
          'Auke',
        ],
      },
      {
        lga: 'Ado',
        cities: ['Igumale'],
      },
      {
        lga: 'Buruku',
        cities: [
          'Buruku',
          'Etilo',
          'Mbaakura',
          'Binev',
          'Mbaade',
          'Mbaatirkya',
          'Mbarkyongo',
          'Mbaazager',
          'Mbarkyongo',
          'Mbatyough',
          'Mbaya',
          'Mbayaka',
          'Akpanta',
          'Shorov',
        ],
      },
      {
        lga: 'Gboko',
        cities: [
          'Gboko',
          'Igyorov',
          'Mbaa Varakaa',
          'Mbaanku',
          'Mbadam',
          'Mbakper',
        ],
      },
      {
        lga: 'Guma',
        cities: [
          'Gbajimba',
          'Mbaawa',
          'Mbabai',
          'Mbasaan',
          'Mbagwen',
          'Uyiev',
          'Daudu',
          'Torkula',
          'Kase Yough',
          'Abinsi',
          'Mbabegha',
          'Agasha',
        ],
      },
      {
        lga: 'Gwer West',
        cities: [
          'Naka',
          'Aondoana',
          'Agagbe',
          'Naji Camp',
          'Jimba',
          'Bunka',
          'Kule',
          'Yonov',
          'Mbakpa',
          'Raav',
          'Njiriv',
          'Ingohov',
          'Ikyande',
          'Enger',
        ],
      },
      {
        lga: 'Gwer East',
        cities: ['Aliade', 'Yonor', 'Ngyonov', 'Nijiriv', 'Raav', 'Mbakpa'],
      },
      {
        lga: 'Katsina-Ala',
        cities: [
          'Katsina-Ala',
          'Katsina Ota',
          'Gbor',
          'Ammatu',
          'Tor Donga',
          'Abaji',
          'Sai',
          'Harga',
          'Mbaton',
          'Gbise',
        ],
      },
      {
        lga: 'Konshisha',
        cities: [
          'Tse-Agberagba',
          'Gungul',
          'Mbavaa',
          'Aba',
          'Abagi',
          'Ko',
          'Aduu',
        ],
      },
      {
        lga: 'Kwande',
        cities: [
          'Adikpo',
          'Nanev',
          'Turan',
          'Ikurave-Ya',
          'Shangev-Ya',
          'Tse-Gum-Mbayevikyaior',
          'Ahile/Akende',
          'Ahundu',
          'Dio',
        ],
      },
      {
        lga: 'Logo',
        cities: [
          'Ugba',
          'Torov',
          'Mbaterem',
          'Ucha',
          'Gaambe',
          'Tiev',
          'Ngenev',
          'Ugondo',
          'Tongov',
          'Kpav',
          'Gambe-Va',
          'Kyutan-Tiev',
        ],
      },
      {
        lga: 'Makurdi',
        cities: [
          'Makurdi',
          'Adaka',
          'Adeke',
          'Ajam',
          'Agbadu',
          'Agbeshir',
          'Agenada',
          'Akaan',
          'Aki',
          'Akigwe',
          'Akpehe',
          'Akume',
          'Alla',
          'Anter',
        ],
      },
      {
        lga: 'Obi',
        cities: [
          'Obarike-Ito',
          'Ito',
          'Agwatashi',
          'Adudu',
          'akanga',
          'Uwokwu',
          'Igede',
        ],
      },
      {
        lga: 'Ogbadibo',
        cities: ['Otukpa', 'Ovakan', 'Owukpa'],
      },
      {
        lga: 'Oju',
        cities: [
          'Oju',
          'Uwokwu',
          'Adega',
          'Abelega',
          'Abofutu',
          'Ameka',
          'Akunda',
          'Adiko',
        ],
      },
      {
        lga: 'Okpokwu',
        cities: [
          'Okpoga',
          'Ichanna',
          'Orokam',
          'Otukpa',
          'Owukpa',
          'Okpoga',
          'Edumoga',
        ],
      },
      {
        lga: 'Ohimini',
        cities: [
          'Idekpa',
          'Onyagede',
          'Enumona',
          'Ogoli',
          'Ogande',
          'Umonomi',
          'Okpiko',
          'Iyaya',
          'Idekpa',
          'Awume',
          'Ikpoke',
          'Ogudu',
        ],
      },
      {
        lga: 'Oturkpo',
        cities: [
          'Oturkpo',
          'Ugboju Ehole',
          'Ugboju icho',
          'Ugboju otehe',
          'Adoka Icho',
          'Adoka Itaje',
          'Ewulo',
          'Okete',
          'Oturkpo East',
          'Oturkpo West',
        ],
      },
      {
        lga: 'Tarka',
        cities: [
          'Wannune',
          'Tarka',
          'Mbaajir',
          'Akaa',
          'Mbaigba',
          'Mbaayo',
          'Tongor',
          'Yandev',
          'Ipav',
          'Mbayion',
          'Mbalagh',
          'Mbatie',
          'Kusuv',
          'Utur',
          'Shorov',
          'Mbagen',
          'Mbatiav',
          'Mbatierev',
        ],
      },
      {
        lga: 'Ukum',
        cities: [
          'Sankera',
          'Borikyo',
          'Aterayange',
          'Mbatian',
          'Uvan',
          'Lumbur',
          'Mbazum',
          'Ituuluv',
          'Tsaar',
          'Mbayenge',
          'Ugbadan',
          'Kendav',
          'Azendesh',
        ],
      },
      {
        lga: 'Ushongo',
        cities: [
          'Lessel',
          'Mbagba',
          'Mbakuha',
          'Ikov',
          'Mbaikyaa',
          'Ushongo',
          'Utange',
          'Atirkyese',
          'Mbaivende',
        ],
      },
      {
        lga: 'Vandeikya',
        cities: [
          'Vandeikya',
          'Mindev',
          'Mbaka Ange',
          'Mbaduka',
          'Mbagbera',
          'Mbayongo',
          'Mbara',
          'Ute',
          'Mbava',
          'Tsambe',
        ],
      },
    ],
  },
  northeast: {
    borno: [
      {
        lga: 'Abadam',
        cities: [
          'Malumfatori',
          'Banowa',
          'Jabullam',
          'Fuguwa',
          'Arege',
          'Yau',
          'Yawa Kura',
          'Mollam Kaunari',
          'Kudokurgu',
        ],
      },
      {
        lga: 'Askira/Uba',
        cities: [
          'Askira',
          'Bagiau',
          'Chul',
          'Dum Bam',
          'Giwa Kir Koma',
          'Jimbulumu',
          'Kauthlama',
          'Njoma',
          'Uba',
          'Uwataku',
          'Yimirali',
          'Dille',
          'Gegombi',
          'Huyum',
          'Kuhi',
        ],
      },
      {
        lga: 'Bama',
        cities: [
          'Bama',
          'Kaigamari',
          'Zarawuyaku',
          'Andara',
          'Ajiri Wulba',
          'Buduwa',
          'Jere',
        ],
      },
      {
        lga: 'Bayo',
        cities: [
          'Biriyel',
          'Balbaya',
          'Fikayel',
          'Gamadadi',
          'Jara Dali',
          'Jara Gol',
          'Limanti',
          'Teli',
          'Wuyo',
          'Zara',
        ],
      },
      {
        lga: 'Biu',
        cities: [
          'Biu',
          'Zarawuyaku',
          'Waka',
          'Mandara',
          'Abdu',
          'Garwashina',
          'Tabra',
          'Burutai',
          'Dadin Kowa',
          'Dugja',
          'Garubula',
          'Gur',
          'Kenken',
          'Mandara Girau',
          'Miringa',
          'Sulumthla',
          'Yawi',
        ],
      },
      {
        lga: 'Damboa',
        cities: [
          'Damboa',
          'Ajign',
          'Azur',
          'Multe',
          'Forfor',
          'Bego',
          'Yerwa',
          'Ngurna',
          'Gumsuri',
          'Misakurbudu',
          'Kafa',
          'Mafi',
          'Mulgwai',
          'Kopchi',
          'Nguda',
          'Wuyaram',
          'Wawa',
          'Korede',
        ],
      },
      {
        lga: 'Dikwa',
        cities: [
          'Dikwa',
          'Sheffri',
          'Boboshe',
          'Dikwa',
          'Gajibo',
          'Magarta',
          'Mallam Maja',
          'Mudu',
          'Kaza',
          'Muliye',
          'Jemuri',
          'Ngudoram',
          'Sogoma',
          'Afuye',
          'Ufaye',
          'Gujile',
        ],
      },
      {
        lga: 'Gubio',
        cities: [
          'Gubio',
          'Ardimini',
          'Dabira',
          'Felo',
          'Gamowo',
          'Gazabure',
          'Kingowa',
          'Ngetra',
          'Zowo',
        ],
      },
      {
        lga: 'Guzamala',
        cities: [
          'Gwoza',
          'Ashigashia',
          'Balangaje',
          'Balazala',
          'Barawa',
          'Bokko',
          'Bulabulin',
          'Duma',
          'Falagwe',
          'Gadful',
          'Bubayawa Gudul',
          'Ngoshe Pulka',
          'Ashigashiya',
          'Bita',
          'Izge',
          'Dure',
          'Wala',
          'Warabe',
        ],
      },
      {
        lga: 'Hawul',
        cities: [
          'Azare',
          'Sakwa',
          'Kwajaffa Hang Kwaya-Bur Tanga-Rumta',
          'Marama',
          'Kidang',
          'Pama',
          'Whitambaya',
          'Puba',
          'Vidau',
          'Lokoja',
          'Hema',
          'Hawul',
          'Shaffa',
        ],
      },
      {
        lga: 'Jere',
        cities: [
          'Khaddamari',
          'Dala Lawanti',
          'Dusuman',
          'Gamboru',
          'Gomari',
          'Gongulong',
          'Jere',
          'Koshebe',
          'Lawanti',
          'Maimusari',
          'Masu',
          'Ngudda',
          'Tuba',
        ],
      },
      {
        lga: 'Kaga',
        cities: [
          'Benisheikh',
          'Afa',
          'Borgozo',
          'Dogoma',
          'Jalori',
          'Dongo',
          'Galangi',
          'Guwo',
          'Karagaru',
          'Mainok',
          'Marguba',
          'Ngamdu',
          'Shettimari',
          'Tobolo',
          'Wajiro',
          'Burgumma',
          'Wassaram',
        ],
      },
      {
        lga: 'Kala/Balge',
        cities: [
          'Rann',
          'Kalam',
          'Kulakula',
          'Kutilar',
          'Mada',
          'Moholo',
          'Masana',
          'Maleri',
          'Mokholo',
          'Sabba',
          'Sigal',
          'Tilam',
        ],
      },
      {
        lga: 'Konduga',
        cities: [
          'Konduga',
          'Lamboa',
          'Bazamri',
          'Dalori',
          'Kellumiri',
          'Konduga',
          'Malari',
          'Ngalimari',
          'Wanori',
          'Yabal',
          'Garu',
          'Auno',
          'Chabbol',
          'Wanori',
          'Dawa',
          'Kangamari',
          'Jewu',
        ],
      },
      {
        lga: 'Kukawa',
        cities: [
          'Kukawa',
          'Alagarno',
          'Baga',
          'Kanembu Adua Ajiri',
          'Alagama',
          'Bundur',
          'Dogoshi',
          'Doro',
          'Duguri',
          'Kauwa',
          'Kekeno',
          'Kukawa',
          'Moduari',
          'Barwari',
          'Yoyo',
        ],
      },
      {
        lga: 'Kwaya Kusar',
        cities: [
          'Kwaya Kusar',
          'Gondi',
          'Kusar',
          'Gusi',
          'Billa',
          'Guwal',
          'Kubuku',
          'Kurba',
          'Kwaya Kusar',
          'Peta',
          'Wada',
          'Yimrthalang',
          'Algarno',
        ],
      },
      {
        lga: 'Mafa',
        cities: [
          'Masu',
          'Mujigine',
          'Tamsu',
          'Ngamdua',
          'Anadua',
          'Kajari',
          'Loslari',
          'Mafa Nguranna',
          'Mafa',
          'Abbari',
          'Mbuta',
          'Mijigine',
          'Siguabuya',
          'Umarari',
        ],
      },
      {
        lga: 'Magumeri',
        cities: [
          'Magumeri',
          'Hoyo',
          'Magumeri',
          'Ayi',
          'Yasku',
          'Furram',
          'Borno Yesu',
          'Gaji Ganna',
          'Chin',
          'Gowa',
          'Ngubula',
          'Ngamma',
          'Kavevam',
          'Kalizoram',
        ],
      },
      {
        lga: 'Maiduguri',
        cities: [
          'Maiduguri Urban',
          'Bolori',
          'Bulablin',
          'Gamboru Liberty',
          'Gwange',
          'Shehiri',
          'Mafoni',
          'Limanti',
          'Lamisula',
          'Jabba Mari',
        ],
      },
      {
        lga: 'Marte',
        cities: [
          'Marte',
          'Ala',
          'Alla Lawanti',
          'Borsori',
          'Gumna',
          'Kulli',
          'Kirenowa',
          'Mawulli',
          'Njine',
          'Zaga',
          'Kabuluwa',
        ],
      },
      {
        lga: 'Mobbar',
        cities: [
          'Damasak',
          'Chamba',
          'Asaga',
          'Mobbar',
          'Diju',
          'Kaveto',
          'Layi',
          'Zanna Umorti',
          'Ghashagar',
        ],
      },
      {
        lga: 'Monguno',
        cities: [
          'Monguno',
          'Kumalia',
          'Damakuli',
          'Kaguram',
          'Mintar',
          'Mofio',
          'Ngurno',
          'Sure',
          'Wulo',
          'Yele',
          'Zulum',
        ],
      },
      {
        lga: 'Ngala',
        cities: [
          'Gambolu',
          'Fuye',
          'Ngala',
          'Ndufu',
          'Sagir',
          'Tunokalia',
          'Warshele',
          'Wulgo',
          'Rana',
          'Wurge',
          'Old Gamboru',
          'Logumare',
        ],
      },
      {
        lga: 'Nganzai',
        cities: [
          'Gajiram',
          'Nganzai',
          'Alarge',
          'Damaram',
          'Gadai',
          'Kuda',
          'Kurnawa',
          'Maiwa',
          'Miye',
          'Sugundure',
          'Gajiram',
          'Sabsabuwa',
        ],
      },
      {
        lga: 'Shani',
        cities: [
          'Shani',
          'GAsi',
          'Buma',
          'Bargu',
          'Lakundum',
          'Gora',
          'Gwolasho',
          'Gwashaka',
          'Kombo',
          'Kubo',
          'Kwaba',
          'Wokama',
          'Salifawa',
        ],
      },
    ],
    gombe: [
      {
        lga: 'Akko',
        cities: [
          'Kumo',
          'Gona',
          'Pindiga',
          'Garin',
          'Garba Jalingo',
          'Jauro',
          'Tukur',
          'Kembu',
          'Panda',
          'Lergo',
          'Mararraban-Tumu',
        ],
      },
      {
        lga: 'Balanga',
        cities: [
          'Talasse',
          'Bambam',
          'Bangu',
          'Cham-Mwona',
          'Chum-Kindiyo',
          'Daduya Hill',
          'Dala-Waja',
          'Degri Dong',
          'Gasi',
          'Gelengu',
          'Kulani',
          'Nyuwar',
          'Refele',
        ],
      },
      {
        lga: 'Billiri',
        cities: [
          'Billiri',
          'Billiri-Tangale',
          'Ayabu',
          'Banganje',
          'Bare',
          'Kalmai',
          'Kulkul',
          'Laberpit',
          'Lakalkal',
          'Lamugu',
          'Landongor',
          'Lanshi Daji',
          'Pade Kungu',
        ],
      },
      {
        lga: 'Dukku',
        cities: [
          'Dukku',
          'Jamani Kaigamari',
          'Gombe Abba',
          'Hashidu',
          'Bawwa',
          'Balikaje',
          'Bomala',
          'Daminya',
          'Dawiya',
          'Du',
          'Jangira',
          'Kokkobe',
          'Kuni Walowa',
          'Wuro',
          'Bali',
          'Tara',
          'Yaufa',
          'Zego/Kunde',
        ],
      },
      {
        lga: 'Kaltungo',
        cities: [
          'Kaltungo',
          'Awak',
          'Bagaruwa',
          'Bwara',
          'Daura',
          'Dodonruwa',
          'Dundaye',
          'Garin Bako',
          'Garin Barau',
          'B/Kaltin',
          'Okshenda',
        ],
      },
      {
        lga: 'Shomgom',
        cities: [
          'Boh',
          'Burak',
          'Filiya',
          'Bango',
          'Bangunji',
          'Bikutture',
          'Bikwala',
          'Bishiwai',
          'Dilange(Dutse)',
          'Kalo',
          'Kulan',
          'Laluwa',
          'Najeji',
          'Suli',
          'Yelchen-Yelchen',
        ],
      },
      {
        lga: 'Funakaye',
        cities: [
          'Bajoga',
          'Ashaka',
          'Badadi',
          'Bage',
          'Bulturi',
          'Gulwari',
          'Lambo Dashi',
          'W.Nai',
          'Yayaru',
          'Zadawa',
          'Abuku',
          'Baba Zur',
          'Bajoga',
        ],
      },
      {
        lga: 'Gombe',
        cities: [
          'Gombe',
          'Arawa',
          'Doma',
          'Gabukku',
          'Inna',
          'Manawashi',
          'Pantami',
          'Arawa',
          'Doma',
          'Gabukku',
          'Manawashi',
          'Pantami',
          'Ajiya',
          'Bajoga',
        ],
      },
      {
        lga: 'Nafada/Bajoga',
        cities: [
          'Nafada',
          'Langa',
          'Mada',
          'Maru',
          'Papa',
          'Shole',
          'Shonganaawo',
          'Suka',
          'Tondi',
          'Wokollu',
          'Zindir',
          'Zangoma Kyari',
          'Kiyayo',
          'Kuka',
          'Lafiyawo',
        ],
      },
      {
        lga: 'Yamaltu/Delta',
        cities: [
          'Deba',
          'Dangar',
          'Dumbu',
          'Jannawo',
          'Kakkau',
          'Kanawa',
          'Kunnuwal',
          'Kuri',
          'Lambam',
          'Lano',
          'Nasarawo',
          'Nono M. Isa',
          'Poli',
          'Saruje',
          'Wajari Jodoma',
        ],
      },
    ],
  },
  northwest: {
    jigawa: [
      {
        lga: 'Auyo',
        cities: [
          'Auyo',
          'Ayama',
          'Ayen',
          'Gamasarka',
          'Gatafa',
          'Kafur',
          'Tsidir',
          'Auyakayi',
          'Unik',
          'Gamfori',
        ],
      },
      {
        lga: 'Babura',
        cities: [
          'Babura',
          'Batali',
          'Dorawa',
          'Kanya',
          'Gasakoh',
          'Kyambo',
          'Takwasa',
          'Insharuwa',
          'Kazunzumi',
        ],
      },
      {
        lga: 'Birni Kudu',
        cities: [
          'Kangire',
          'Birni Kudi',
          'Kantoga',
          'Kiyako',
          'Kwangwara',
          'Lafia',
          'Sundimina',
          'Surko',
          "Unguwan'ya",
          'Wurno',
          'Yalwan Damai',
        ],
      },
      {
        lga: 'Biriniwa',
        cities: [
          'Biriniwa',
          'Bata',
          'Brimiwa',
          'Diginsa',
          'Fagi',
          'Kachallani',
          'Karanka',
          'Kazura',
          'Matamu',
          'Nguwa',
          'Machinamari',
          'Dangwaleri',
        ],
      },
      {
        lga: 'Buji',
        cities: [
          'Gantsa',
          'Buji',
          'Ahoto',
          'Falageri',
          'Gantsa',
          'Churbun',
          'Kawaya',
          'Kukuma',
          'Madebe',
          'Tukur',
          'Klelen Kudu',
        ],
      },
      {
        lga: 'Dutse',
        cities: [
          'Dutse',
          'Duru',
          'Dundubus',
          'Jigwar Tsada',
          'Kudia',
          'Karnaya',
          'Limawa',
          'Madobi',
          'Chamo',
          'Abaya',
          'Sakwaya',
        ],
      },
      {
        lga: 'Gagarawa',
        cities: [
          'Gagarawa',
          'Gagarawa Gari',
          'Tasha Garin',
          'Chiroma Kare',
          'Balatu',
          'Madaka',
          'Medu',
          'Maiaduwa',
          'Maikilili',
          'Yalawa',
          'Zarada',
        ],
      },
      {
        lga: 'Garki',
        cities: [
          'Garki',
          'Buduru',
          'Garki Doko',
          'Gwarzon-Garki',
          'Kanya',
          'Kargo',
          'Muku Rafin',
          'Marke',
          'Siyori',
          'Kore',
        ],
      },
      {
        lga: 'Mel',
        cities: [
          'Gumen',
          'Dan-Ama',
          'Balkamy',
          'Danzomo',
          'Garin Alhaji',
          'Baikarya',
          'Garin Gambo',
          'Gusan',
          'Hammado',
          'Kofar Arewa',
          'Zango',
          'Kofar Yamma',
        ],
      },
      {
        lga: 'Guri',
        cities: [
          'Guri',
          'Abunabo',
          'Dawa',
          'Adiyani',
          'Garbagal',
          'Kadira',
          'Lafiya',
          'Musari',
          'Matara-baba',
          'Margadu',
        ],
      },
      {
        lga: 'Gwaram',
        cities: [
          'Gwaram',
          'Dingaya',
          'Fagam',
          'Basirka',
          'Farin Dutse',
          'Gwaram-Tsohuwa',
          'Kwandiko',
          'Maruta',
          'Sara',
          'Tsangarwa',
          'Zandan Nagogo',
        ],
      },
      {
        lga: 'Gwiwa',
        cities: [
          'Gwiwa',
          'Dabi',
          'Darina',
          'Buntus',
          'Guntai',
          'Yola',
          'Zaumar',
          'Sainawa',
          'Shafe',
          'Korayel',
        ],
      },
      {
        lga: 'Hadejia',
        cities: [
          'Hadejia',
          'Kasuwar',
          'Kofa',
          'Dubantu',
          'Atafi',
          'Majema',
          'Mattsaro Rumfa',
          'Sabon garu',
          'Yankoli',
          'Yayari',
          'Kusuwar',
          'Kuda',
          'Gagulmari',
          'Gazulmari',
          'Hadejia Jama',
          'Kofar Arewa',
          'Kofar Gabas',
          'Makwalla',
        ],
      },
      {
        lga: 'Jahun',
        cities: [
          'Jahun',
          'Aujara',
          'Gunka',
          'Gunza Tazara',
          'Harbo Sabuwa',
          'Harbo-Tsohuwa',
          'Idanuna',
          'Jahun',
          'Kale',
          'Jabarna',
          'Gangawa',
        ],
      },
      {
        lga: 'Kafin',
        cities: [
          'kafin',
          'Jabo',
          'Zago',
          'Sarawa',
          'Ruba',
          'Majawa',
          'Balangu',
          'Kazalewa',
          'Dumadumin Toka',
          'Gafaya',
          'Mezan',
          'Kafin hausa',
        ],
      },
      {
        lga: 'Kaugama Kazaure',
        cities: [
          'Kaugama',
          'Askandu',
          'Yalo',
          'Marke',
          'Jarkasa',
          "Ja'e",
          'Hadin',
          'Unguwas jibin',
          'Dakaiyawa',
          'Dabuwaran',
        ],
      },
      {
        lga: 'Kiri Kasamma',
        cities: [
          'Kiri Kasamma',
          'Bulunchai',
          'Baturiya',
          'Gayin Kiri',
          'Kasamma',
          'Madachi',
          'Tarabu',
          'Tscheguwa',
        ],
      },
      {
        lga: 'Kiyawa',
        cities: [
          'Kiyawa',
          'Garko',
          'Farke',
          'Guruduba',
          'Katanga',
          'Kakuta',
          'Kwanda',
          'Kwanda',
          'Maje',
          'Tsurma',
          'Andarza',
          'Abalogo',
        ],
      },
      {
        lga: 'Maigatari',
        cities: [
          'Maigatari',
          'Balarabe',
          'Fulata',
          'Dankumbo',
          'Galadi',
          'Jajeri',
          'Madana',
          'Maigatari Arewa',
          'Kudu',
          'Matoya',
          'Turbus',
          'Kukayasku',
        ],
      },
      {
        lga: 'Malam Madori',
        cities: [
          'Malam Madori',
          'Dunari',
          'Fulata',
          'garin Gabas',
          'Shaiya',
          'Tonikutara',
          'Fateka Akurya',
          'Tagwaro',
          'Tashena',
        ],
      },
      {
        lga: 'Miga',
        cities: [
          'Miga',
          'Harbo',
          'Hantsu',
          'Koya',
          'Sabon-Gari',
          'Sansani',
          'yanduna',
          'Zareku',
          'Tsakuwawa',
          'Dangyatin',
        ],
      },
      {
        lga: 'Ringim',
        cities: [
          'Ringim',
          'Sankara',
          'Tofa',
          'Karshi',
          'Kyarama',
          'Dabi',
          'Chai-chai',
          'Kafin Babushe',
          'Yanditshe',
          'Sintilmawa',
        ],
      },
      {
        lga: 'Roni',
        cities: [
          'Roni',
          'Baragumi',
          'Dansure',
          'Fara',
          'Gora',
          'Kwaita',
          'Sankau',
          'Tunas',
          'Yanzaki',
          'Zugai',
          'Amaryawa',
          'Roni',
        ],
      },
      {
        lga: 'Sule-Tankarkar',
        cities: [
          'Sule-Tankarkar',
          'BaAmangaragumi',
          'Dangwanki',
          'Danlabi',
          'Danzomo',
          'Jeke',
          'Shabaru',
          'Yandamo',
          'Albasu',
        ],
      },
      {
        lga: 'Taura',
        cities: [
          'Taura',
          'Ajaura',
          'Chukuto',
          'Gujungu',
          'Kiri',
          'Maja',
          'Majiya',
          'Chakwaikwaiwa',
          'Garin Yaya',
        ],
      },
      {
        lga: 'Yankwashi',
        cities: [
          'Yankwashi',
          'Belas',
          'Dawan-Gawo',
          'Gurjiya',
          'Gwarta',
          'Kuda',
          'Ringim',
          'Karkarna',
          'Achilafiya',
          'Zunbumba',
        ],
      },
    ],
    kaduna: [
      {
        lga: 'Birni-Gwari',
        cities: [
          'Birni-Gwari',
          'Dogon Dawa',
          'Gayam',
          'Kutemesi',
          'Magajin',
          'Tabanni',
          'Kuyelo',
        ],
      },
      {
        lga: 'Chikun',
        cities: [
          'Kujama',
          'Sabon-Tasha',
          'Chikin',
          'Kakau',
          'Kuriga',
          'Nassarawa',
          'Rido',
          'gwagwada',
          'Narayi',
          'Ung. Yelwa',
        ],
      },
      {
        lga: 'Giwa',
        cities: [
          'Giwa',
          'Katangi',
          'Kadage',
          'Kidandan',
          'Yakawada',
          'Shika',
          'Pan Hauya',
          'Idasu',
          'Gangara',
          'Galadimawa',
          'Danmahawayi',
        ],
      },
      {
        lga: 'Igabi',
        cities: [
          'Turunku',
          'Afaka',
          'Sabon-Birnin Daji',
          'Kwarau',
          'Rigachikun',
          'Kerawa',
          'Kawaraji',
          'Gadan Gayan',
          'Birnin Yero',
        ],
      },
      {
        lga: 'Ikara',
        cities: [
          'Ikara',
          'Saya-Saya',
          'Saulawa',
          'Paki',
          'Pala',
          'Rumi',
          'Kuya',
          'Auchan',
          'Kurmin Kogi',
          'Furana',
        ],
      },
      {
        lga: 'Jaba',
        cities: [
          'Kwoi',
          'Sambam',
          'Sabchem',
          'Sabzuro',
          'Nduyah',
          'Nok',
          'Fai',
          'Fada',
          'Dura',
          'Daddu',
          'Chori',
          'Bitaro',
        ],
      },
      {
        lga: "Jema'a",
        cities: [
          'Kafanchan',
          'Asso',
          'Kagoma',
          'Godogodo',
          'Jagindi',
          'Kaninkon',
          'Maiqizo',
          'Bedde',
          'Atutu',
          'Takau',
          'Kafanchan',
          "Jema'a",
        ],
      },
      {
        lga: 'Kachia',
        cities: [
          'Kachia',
          'Agunu',
          'Kwaturu',
          'Awon',
          'Ankwa',
          'Gumel',
          'Katari',
          'Doka',
          'Bishin',
          'Gidan Tagwai',
          'Kurmin Musa',
          'Sabon Sarki',
        ],
      },
      {
        lga: 'Kaduna North',
        cities: [
          'Doka',
          'Gaji',
          'Gabasawa',
          'Shaba',
          'Hayin Bank',
          'Kabala Costain',
          'Kawo',
          'Unguwan Dosa',
          'Unguwan Liman',
          'Unguwan Shanu',
          'Kaduna',
        ],
      },
      {
        lga: 'Kaduna South',
        cities: [
          'Makera',
          'Tudan wada',
          'Tudan Nuwapa',
          'Sabon Gari',
          'Kakuri Hausa',
          'Kakuri Gwari',
          'Barnawa',
          'Badoko',
        ],
      },
      {
        lga: 'Kagarko',
        cities: [
          'Kagarko',
          'Jeje',
          'Iddah',
          'Aribi',
          'kukui',
          'Kushe',
          'Kurmin Jubrin',
        ],
      },
      {
        lga: 'Kajuru',
        cities: [
          'Kajuru',
          'Buda',
          'Maro',
          'Rimau',
          'Tantatu',
          'Kutana',
          'Kasuwan',
          'Magani',
          'Kallah',
          'Idon',
          'Afogo',
        ],
      },
      {
        lga: 'Kaura',
        cities: [
          'kaura',
          'Kukum Daji',
          'Fadan Takad',
          'Kadarko',
          'Bondong',
          'Garaji',
          'Fadan Attakar',
          'Fada Ciki Gari',
          'Kaura',
          'Manchok',
          'Zankan',
        ],
      },
      {
        lga: 'Kauru',
        cities: [
          'kauru',
          'Dawaki',
          'Pari Makami',
          'Geshere',
          'Bondong',
          'Kamaru',
          'Kauru West',
          'Kauru East',
          'Bital',
          'Badurun Sama',
          'Dawakasuwa',
        ],
      },
      {
        lga: 'Kubau',
        cities: [
          'Auchau',
          'Zuntu',
          'Pambegua',
          'Zabi',
          'Kargi',
          'Kamaru',
          'Karreh',
          'Haskiya',
          'Damau',
          'Dutsen Wai',
          'Anchau',
        ],
      },
      {
        lga: 'Kudan',
        cities: [
          'Hunkuyi',
          'Kudan',
          'Hunkuyi',
          'Likoro',
          'Zabi',
          'Sabon Gari',
          'Doka',
          'Taba',
          'Garu',
          'Kauran Wali',
        ],
      },
      {
        lga: 'Lere',
        cities: [
          'Lere',
          'Saminaka',
          'Sabon Birnin',
          'Ramin Kura',
          'Lazuru',
          'Kayarda',
          'Yar Kasuwa',
          'Abadawa',
          'Gure-Kahugu',
        ],
      },
      {
        lga: 'Makarfi',
        cities: [
          'Makarfi',
          'Nasarawan Doya',
          'Ruma',
          'Gimi',
          'Gazara',
          'Meyere',
          'Gubuchi',
          'Dorayi',
          'Durum',
          'Gwanki',
        ],
      },
      {
        lga: 'Sabon-Gari',
        cities: [
          'Sabon-Gari',
          'Gwantu',
          'Aboro',
          'Ayu',
          'Wasa Station',
          'Ninzam South',
          'Ninzam West',
          'Ninzam North Nnadu',
          'Bokana',
          'Arak',
          'Sanga',
          'Fadan Karshi',
          'Fadan Ninzo',
        ],
      },
      {
        lga: 'Soba',
        cities: [
          'Maigama',
          'Saba',
          'Turawa',
          'Richifa',
          'Rahama',
          'Dan Wata',
          'Garun Gwanki',
          'Gimba',
          'Kinkiba',
          'Kwassallo',
          'Maigana',
          'Gamagira',
        ],
      },
      {
        lga: 'Zango-Kataf',
        cities: [
          'Zonkwo',
          'Zonzon',
          'Zango Urban 1',
          'Zango Urban 2',
          'Zaman Dabo',
          'Gidan Jatau',
          'Gora',
          'Kamantan',
          'Kamaru Ikulu',
          'Madakiya',
          'Unguwar Gaiya',
          'Ungwan Rimi',
          'Zango Kataf',
        ],
      },
      {
        lga: 'Zaria',
        cities: [
          'Zaria',
          'Wucicciri',
          'Kwarbai',
          'Kaura',
          'Dambo',
          'Dutsen Abba',
          'Kufena',
          'Tudun Wada',
          'Tukur-Tukur',
          'Gyallesu',
          'Ung.Juma',
          'Limanchi',
          'Ung. Fatika',
          'Limancin Kona',
        ],
      },
    ],
    kano: [
      {
        lga: 'Ajingi',
        cities: [
          'Ajingi',
          'Gurduba',
          'Dabin',
          'Chula',
          'Dundun',
          'Kanava',
          'Gafasa',
          'Bafare',
          'Kunkurawa',
          'Bia',
          'Unggawar',
        ],
      },
      {
        lga: 'Albasu',
        cities: [
          'Albasu Central',
          'Saya-Saya',
          'Hungu',
          'Tsangaya',
          'Gagarame',
          'Faragai',
          'Daho',
          'Fando',
          'Bataiya',
          'Chamarana',
        ],
      },
      {
        lga: 'Bagwai',
        cities: [
          'Gogo',
          'Bagwai',
          'Rimi-Dako',
          'Dagga',
          'Wuro',
          'Kiyawa',
          'Gadanya',
          'Kwajali',
          'Romo',
          'Sare-Sare',
        ],
      },
      {
        lga: 'Bebeji',
        cities: [
          'Bebeji',
          'Tariwa',
          'Ranta',
          'Ranka',
          'Wak',
          'Anadariya',
          'Kuki',
          'Kofa',
          'Gargari',
          'Durmawa',
          'Damau',
          'Rahama',
          'Baguda',
        ],
      },
      {
        lga: 'Bichi',
        cities: [
          'Bichi',
          'Yallami',
          'Badume',
          'Fagolo',
          'Kaukau',
          'Kyayli',
          'Muntsira',
          'Saye',
          'Waire',
          'Danzabuwa',
        ],
      },
      {
        lga: 'Bunkure',
        cities: [
          'Bunkure',
          'bono',
          'Sanda',
          'Kulluwa',
          'Gafam',
          'Guriya',
          'Chirin',
          'Bakum',
          'Kumurya',
        ],
      },
      {
        lga: 'Dala',
        cities: [
          'Gwammaja',
          'Ruwa',
          'Kofa',
          'Mazugal',
          'Gobirawa',
          'Dogon-Nama',
          'Bakin-Ruwa',
          'Adakawa',
          'Yalwa',
          'Kantudu',
          'Kabuwa',
        ],
      },
      {
        lga: 'Dambatta',
        cities: [
          'Dambatta',
          'Sansa',
          'Saidawa',
          'Gwanda',
          'Goron',
          'Maje',
          'Gwarabjawa',
          'Fagwalawa',
          'Kove',
          'Ajumawa',
        ],
      },
      {
        lga: 'Dawakin Kudu',
        cities: [
          'Dawaki Kudu',
          'Yankatsari',
          'Zogarawa',
          'Yargaya',
          'Yanbarau',
          'Unguwar',
          'Duniya',
          'Tsakuwa',
          'Tamburawa',
          'Jido',
          'Gano',
          'Dosan',
          'Danwakiji',
          'Dawaki',
          'Dabagiwa',
          'Dabar Kwari',
          'Dawoki',
        ],
      },
      {
        lga: 'Dawakin Tofa',
        cities: [
          'Dawaki',
          'Marke',
          'Jalli',
          'Kwa',
          'Gargari',
          'Ganduje',
          'Dawaki-West',
          'Dawaki-East',
          'Danguguwa',
          'Tattarawa',
          'Tumfafii',
        ],
      },
      {
        lga: 'Doguwa',
        cities: [
          'Ririwai',
          'Maraku',
          'Dariya',
          'Dagon Kano',
          'Folgove',
          'Ragada',
          'Tagware',
          'Ungnwar',
          'Natsohuwa',
          'Zamabi',
          'Doguwa',
        ],
      },
      {
        lga: 'Fagge',
        cities: [
          'Waje Sub-burbs',
          'Kano',
          'Yammata',
          'Sabon-Gari',
          'Kwadiri',
          'Rijiyar Lemo',
          'Fagge',
        ],
      },
      {
        lga: 'Gabasawa',
        cities: [
          'Zakirai',
          'Yumbu',
          'Tarauni',
          'Joda',
          'Garrun Danga',
          'Gabasawa',
          'Mekiya',
          'Yautara Kudu',
          'Yantan Avewwa',
          'Zugachi',
          'Karmaki',
          'Zakirai',
        ],
      },
      {
        lga: 'Garko',
        cities: [
          'Garko',
          'Gurijiya',
          'Garin-Ahi',
          'Dal',
          'Sarina',
          'Kafin Motamaim',
          'Zakarawav',
          'Raba',
          'Kwas',
          'Katurmari',
        ],
      },
      {
        lga: 'Garum Mallam',
        cities: [
          'Garum Mallam',
          'Jobawa',
          'Kadawa',
          'Yad',
          'Akwani',
          'Makwaro',
          'Yalwan Yadakwani',
          'Fankurun',
          'Dorawar',
          'Sallam',
          'Chiromawa',
          'Garum Babba',
          'Garum Molam Kudu',
        ],
      },
      {
        lga: 'Gaya',
        cities: [
          'Gaya',
          'Balan',
          'Garmarya',
          'Gamoji',
          'Gaya-Arewa',
          'Gaya-Kudu',
          'Kademi',
          'Wudiyawa',
          'Shagogo',
          'Maimakawa',
          'Kazurawa',
        ],
      },
      {
        lga: 'Gezawa',
        cities: [
          'Gezawa',
          'Jogana',
          'Gawo',
          'Zango',
          'Tumbau',
          'Wangara',
          'Sarain-Gezawa',
          'Babawa',
          'Ketatwa',
          'Tsamiya-Dabba',
        ],
      },
      {
        lga: 'Gwale',
        cities: [
          'Gwale',
          'Mandawari',
          'Gyaranya',
          'Kabuga',
          'Dandago',
          'Diso',
          'Galadandi',
          'Goron-Dutshe',
          'Kwale',
        ],
      },
      {
        lga: 'Gwarzo',
        cities: [
          'Gwarzo',
          'Sabon-Brini',
          'Kara',
          'Mainika',
          'Madadi',
          'Lakwaya',
          'Kutama',
          'Getso',
          'Gwarzo',
          "Jama'A",
          'Unguwar Tudu',
        ],
      },
      {
        lga: 'Kabo',
        cities: [
          'Kabo',
          'Kamawa',
          'Masnawa',
          'Haauwade',
          'Gude',
          'Gadiya',
          'Garo',
          'Gammo',
          'Durum',
          'Dugabum',
        ],
      },
      {
        lga: 'Kano Municipal',
        cities: [
          'Kofar Kudu',
          'Zartawa',
          'Yakassi Tudun',
          'Wazirchi',
          'Tudun Nufawa',
          'Shashe',
          'Sharada',
          'Shalruchi',
          'Kankarofi',
          'Jakara',
          'Gandum',
          'Albasa',
          'Kano Municipal',
        ],
      },
      {
        lga: 'Karaye',
        cities: [
          'Karaye',
          'Daura',
          'Kwanyawa',
          'Kurugu',
          'Kafin Dafga',
          'Tudun Kaya',
          'Turawa',
          'Yammedi',
          'Karaye',
          'Unguwar Hajji',
        ],
      },
      {
        lga: 'Kibiya',
        cities: [
          'Kibiya',
          'Durba',
          'Kahu Kadigawa',
          'Fassi',
          'Fammar',
          'Kibiya i',
          'Kibiya ii',
          'Nariya',
          'Unguwar',
          'Tarai',
        ],
      },
      {
        lga: 'Kiru',
        cities: [
          'Kiru',
          'Yalwa',
          'Zuwo',
          'Yako',
          'Maroku',
          'Kogo',
          'Kiru Dashi',
          'Dangora',
          'Barawa',
          'Badafi',
          'Bargoni',
          'Banda',
          'Tsaudawa',
        ],
      },
      {
        lga: 'Kumbotso',
        cities: [
          'Kumbosto',
          'Unguwar Rimi',
          'Mariri',
          "Na'ibawa",
          'Panshekara',
          'Guringawa',
          'Danbare',
          'Chirandchi',
          'Challawa',
          'Kureken Sani',
          'Danmaliki',
          'Kumbusto',
        ],
      },
      {
        lga: 'Kunchi',
        cities: [
          'Kunchi',
          'Ridawa',
          'Matan Fada',
          'Shamakawa',
          'Kasuwar',
          'Kuka',
          'Yamdadi Shuwaki',
          'Gwarmi',
          'Bumai',
          'Garin Sheme',
        ],
      },
      {
        lga: 'Kura',
        cities: [
          'Kura',
          'Dalili',
          'Dukawa',
          'Karfi',
          'Gundutche',
          'Dan Hassan',
          'Rigar Duka',
          'Tanawa',
          'Kurunsumau',
        ],
      },
      {
        lga: 'Madobi',
        cities: [
          'Madobi',
          'Burji',
          'Chiinkoso',
          'Daburau Dan Maryame',
          'Dan Danzo',
          'Gari Gazana',
          'Gora',
          'Kafin Agur',
          'Kanwa',
          'Kaura Mata',
          'Kubarachi',
          'Kwankwaso',
          'Ningawa',
          'Rikadawa',
          'Ruga',
          'Yakun',
        ],
      },
      {
        lga: 'Makoda',
        cities: [
          'Koguna',
          'Bakarari Chidari',
          'Danya',
          'Dunawa',
          'Ganji',
          'Jibya',
          'Koguna',
          'Mai-Unguwa',
          'Maitse Dau',
          'Nakarari',
          'Sabon Ruwa',
          'Tabo',
          'Tangaji',
          'Yamawa',
          'Zago',
        ],
      },
      {
        lga: 'Minjibir',
        cities: [
          'Minjibir',
          'Abudakawa',
          'Agalawa',
          'Agarandawa',
          'Azore',
          'Bagurawa',
          'Beguwa',
          'Damusawa',
          'Dauni',
          'Daurawa',
          'Dingin',
          'Dukawa',
          'Dukuji',
          'Dumawa',
          'Farawa',
          'Farke',
        ],
      },
      {
        lga: 'Nasarawa',
        cities: [
          'Bompai',
          'Tudun Murtala',
          'Kawaji',
          'Gama',
          'Dakata',
          'Giginyu',
          'Hotorro North',
          'Hotorro South',
          'Kaira Goje',
          'Nasarawa',
        ],
      },
      {
        lga: 'Rano',
        cities: [
          'Rano',
          'Dawaki',
          'Zurgu',
          'Zinyau',
          'Yalwa',
          'Saji',
          'Rurum Sabon Gari',
          'Rurum Tsohon-Gari',
          'Lausu',
          'Madachi',
        ],
      },
      {
        lga: 'Rimin Gado',
        cities: [
          'Rimin Gado',
          'Tamawa',
          'Sakaratsa',
          'Yalwan',
          'Danziyd',
          'Zango Dan Abdu',
          'Karofin Yashi',
          'Jili',
          'Dugurawawa',
          'Gulu',
          'Butu-Butu',
          'Dawaki-Gulu',
          'Rimi-Gado',
        ],
      },
      {
        lga: 'Rogo',
        cities: [
          'Rogo',
          'Beli',
          'Zoza',
          'Zarewa',
          'Ruwan Bago Sabon Gari',
          'Rogo Ruma',
          'Jajaye',
          'Fulotan',
          'Falgore',
          'Gwangwan',
          'Ruwan Dago',
          'Rogo',
        ],
      },
      {
        lga: 'Shanono',
        cities: [
          'Shanono',
          'Shakogi',
          'Kokiya',
          'Leni',
          'Tsaaure',
          'Kadamu',
          'Goron-Dutshe',
          'Faruruwa',
          'Alajawa',
          'Dutsen-Bakoshi',
          'Shanono',
        ],
      },
      {
        lga: 'Sumaila',
        cities: [
          'Sumaila',
          'Sitti',
          'Masu',
          'Magami',
          'Kanawa',
          'Gediya',
          'Gani',
          'Gala',
          'Rimi',
          'Sumata',
          'Rumo',
          'Garfa',
        ],
      },
      {
        lga: 'Takai',
        cities: [
          'Takai',
          'Zuga',
          'Bagwaro',
          'Fajewa',
          'Faruruwa',
          'Kachako',
          'Karfii',
          'Kuka',
          'Falali',
          'Durbunde',
        ],
      },
      {
        lga: 'Tarauni',
        cities: [
          'Unguwa Uku',
          'Unguwar Gano',
          'Kayen Alu',
          'Giadi',
          'Hotoro',
          'Hudu',
          'Gyadi-Awere',
          'Babban Giji',
          'Darmanawa',
          'Durawa',
          'Tarauni',
        ],
      },
      {
        lga: 'Tofa',
        cities: [
          'Tofa',
          'Doka',
          'Dokadawa',
          'Dutwatsu',
          'fofa',
          'Kadawa',
          'Ginsawa',
          'Kazardawa',
          'Kwami',
          'Lambu',
          'Langel',
          'Rinji',
          'Sabon Gari Katsalle',
          'Yango',
          'Yarimawa',
          'Yanoko',
        ],
      },
      {
        lga: 'Tsanyawa',
        cities: [
          'Tsanyawa',
          'Baje',
          'Bumai',
          'Dadarawa',
          'Dadarawa Tsohuwa',
          'Dakwai',
          'Dumbulum',
          'Farsa',
          'Gozaki',
          'Gurun',
          'Harbau',
          'Jamar',
          'Jigilawa',
          'Kabagiwa',
          'Katsale',
          'Kokai Kuka',
          'Kwandawa',
          'Rafin Tsamiya',
          'Runji',
        ],
      },
      {
        lga: 'Tudun Wada',
        cities: [
          'Tudun Wada',
          'Shuwi',
          'Sumana',
          'Wuna',
          'Yar Fulani',
          'Yar Yasa',
          'Yelwa',
          'Baburi Bul',
          'Burun Burun',
          'Dalawa',
          'Fala',
          'Wambai',
          'Gazobi',
          'Hayindenu',
          'Jammaje',
          'Jandutse',
        ],
      },
      {
        lga: 'Ungogo',
        cities: [
          'Ungogo',
          'Adaraye',
          'Alhrani',
          'Amar Zakawa',
          'Bacirawa',
          'Bagujan',
          'Ciromawa',
          'Dankunkuru',
          'Dausayi',
          'Doka',
          'Dorayi',
          'Fanisau',
          'Garinlya',
          'Gayawa',
          'Gera',
          'Hoto Indabo',
        ],
      },
      {
        lga: 'Warawa',
        cities: [
          'Warawa',
          'Danlassan',
          'Yangizo',
          'Jemagu',
          'Warawa',
          'Imawa',
          'Garin Dau',
          'Tangar',
          'Madari Mata',
        ],
      },
      {
        lga: 'Wudil',
        cities: [
          'Wudil',
          'Utai',
          'Sabon Gari',
          'Darki Lajawa',
          'Kausani',
          'Indabo',
          'Dankaza',
          'Dagumawa',
          'Achika',
        ],
      },
    ],
    katsina: [
      {
        lga: 'Bakori',
        cities: [
          'Bakori',
          'Kakumi',
          'Kandarawa',
          'Kurami/Yankwani',
          'Tsiga',
          'Kabomo',
          'Jargaba',
          'Guga',
          'Dawan Musa',
          'Maraji',
          'Kwantakwaram',
          'Gazara',
          'Barde',
        ],
      },
      {
        lga: 'Batagarawa',
        cities: [
          'Batagarawa',
          'Rarawa',
          'Jino',
          'Kayauki',
          'Tsanni',
          'Yargamji',
          'Ajiwa',
          'Bikiyawa',
          'Dandagoro',
        ],
      },
      {
        lga: 'Batsari',
        cities: [
          'Batsari',
          'Kagara',
          'Abadau',
          'Batsari',
          'Magaji',
          'Kandawa',
          'Madogara',
          'Manawa',
          'Ruma',
          'Wagini',
          'Yauyau/Mailamawa',
          'Yangaiya',
          'Karare',
        ],
      },
      {
        lga: 'Baure',
        cities: [
          'Baure',
          'Agala',
          'Garki',
          'Kagara',
          'Mai-Bara',
          'Yanduna',
          'Taramnawa',
          'Muduri',
          'Unguwar',
          'Babban Mutum',
          'Yanmauuli Rai',
          'Hui',
        ],
      },
      {
        lga: 'Bindawa',
        cities: [
          'Bindawa',
          'Doro',
          'Faru/Dallaji',
          'Gaiwa',
          'Giremawa',
          'Jibawa',
          'Kamri',
          'Shibdawa',
          'Tama/Daye',
          'YYangoro',
        ],
      },
      {
        lga: 'Charanchi',
        cities: [
          'Charanchi',
          'Banye',
          'Doya',
          'Radda',
          'Safana',
          'Ganuwa',
          'Koda',
          'Kuraye',
          'Tsakatsa',
          'Maje',
          'Wayya',
          'Dafara',
          'Kadanye',
          'Kumuye',
          'Kuraje',
          'Tsaski',
          'Yaruku',
          'Yana',
        ],
      },
      {
        lga: 'Dandume',
        cities: [
          'Dandume',
          'Magaji Wando 1 & 2',
          'Dandume 1 & 2',
          'Mahuta 1 & 2',
          'Tumbarkai',
          'Dan-Soda',
          'Dantakari',
          'Ilalla',
          'Jiruwa',
          'Magaji-Wando',
          'Mahuta',
          'Mai Kwama',
        ],
      },
      {
        lga: 'Danja',
        cities: [
          'Danja',
          'Dabai',
          'Danja',
          'Jiba',
          'Kahutu',
          'Tandama',
          'Tsaugamuma(Tsangamawa)',
          'Yakaji',
        ],
      },
      {
        lga: 'Dan Musa',
        cities: [
          'Mai Dobino 1& 2',
          'Dan Ali',
          'Dan Alkima',
          'Dandire 1 & 2',
          'Dan Musa 1 & 2',
          'Mara',
          'Yantumaki',
        ],
      },
      {
        lga: 'Daura',
        cities: [
          'Daura',
          'Daberam',
          'Gurjiya',
          'Sharawa',
          'Maji Yawa',
          'Yarogel',
          'Ganga',
          'Suduji',
          'Bauni',
          'Zari',
          'Bojo',
          'Don-Nakola Garjiya',
          'Dunu',
          'Lambu-Tudu',
          'Jambu',
          'Kalgo',
          'Kamfawa',
          'Kurneji',
        ],
      },
      {
        lga: 'Dutsi',
        cities: [
          'Dutsi',
          'Baugel',
          'Dan Rumai',
          'Sirika',
          'Madawa',
          'Kayawa',
          'Macinawa',
          'Makan Gara',
          'Tashar-Wali',
          'Yamel',
          'Shargalle',
          'Danaunai',
          'Dinya Mai',
          'Dan-kowa',
        ],
      },
      {
        lga: 'Dutsin-Ma',
        cities: [
          'Dutsin-Ma',
          'Bagagadi',
          'Dagelawai',
          'Dan-Ali',
          'Dorawa',
          'Katanga',
          'Dabawa',
          'Kagara',
          'Rayi Faguwa',
        ],
      },
      {
        lga: 'Faskari',
        cities: [
          'Faskari',
          'Mairuwa',
          'Bakarya',
          'Doma',
          'Bagudu',
          'Bele',
          'Bilbis',
          'Karmanje U/Bikka',
          'Fankama',
          'Kogo',
          'Kwabirshawa',
          'Mai Gora',
          'Birnin Kogo',
          "D/Ba'u",
          'Kwakware Sheme',
          'Daudawa',
          'Kanon Haki',
        ],
      },
      {
        lga: 'Funtua',
        cities: [
          'Funtua',
          'Dukke',
          'F/Dadutsi',
          'F/Maikatawa',
          'F/Ta Gabas',
          'F/TaYamma',
          'F/Tanimu',
          'F/Tudu',
          'F/Wawa',
          'Farin',
          'Goya',
          'Illala',
          'Jabiri',
          'maigamiji',
          'Mairuwa',
          'Makere',
          'Maska',
        ],
      },
      {
        lga: 'Ingawa',
        cities: [
          'Ingawa',
          'Agayawa',
          'Bidore',
          'Dara',
          'Yaya',
          'Dugul',
          'Daunaka',
          'Jobe',
        ],
      },
      {
        lga: 'Jibia',
        cities: [
          'Jibia',
          'Farfaru',
          'Mallamawa',
          'Gangara',
          'Kusa',
          'Riko',
          'Yangaiya',
          'Gulbin Baure',
          'Magama',
          'Maje',
          'Mallamawa',
          'Mazanya',
          'Bugaje',
        ],
      },
      {
        lga: 'Kafur',
        cities: [
          'Kafur',
          'Yari-Bori',
          'Masari',
          'Mahuta',
          'Gozaki',
          'Kanya',
          'Dustin Kura',
          'Dantutture',
          'Yar-Talata',
          'Rigaji',
          'Barakai',
          'Dan Kanjiba',
          'Dan Kwaro',
          'Dantige',
          'Dayawa',
          'Dutse',
          'Dutsin-Yanke',
          'Gamzako',
        ],
      },
      {
        lga: 'Kaita',
        cities: [
          'Kaita',
          'Baawa',
          'Dankaba',
          'Dankama',
          'Girka',
          'Matsai',
          'Yandaki',
          'Yanhoho',
          'Abdallawa',
          'Allemi',
          'Bado',
          'Dagon Dawa',
          'Damgamji',
          'Dan bazau',
          'Dan Kunama',
          'Dan Tudu',
          'Dan Kunama',
          'Daurawa',
          'Tsamiye',
          'Dumbasa',
        ],
      },
      {
        lga: 'Kankara',
        cities: [
          'Kankara',
          'Zango',
          'Zabaro',
          'Wawarkaza',
          'Hurya',
          'Burdugau',
          'Dan Murabu Garaji',
          'Dan Maidaki',
          'Gatakawa',
          'Kukasheka',
          'Pauwa',
          'Almajiraiwa',
          'Arewa',
          'Bagoma',
          'Da-Kumeji',
        ],
      },
      {
        lga: 'Kankia',
        cities: [
          'Kankia',
          'Sakuntuni',
          'Rimaye',
          'Tafashiya',
          'Kunduru',
          'Kafin Dangi',
          'Fakuwa',
          'Galadima',
          'Gachi',
          'Gyaza',
          'Magam',
          'Kankia',
          'Tsa',
          'Dan Doro',
          'Gidan Mutum',
        ],
      },
      {
        lga: 'Katsina',
        cities: [
          'Katsina',
          'Wakilin Yamma',
          'Galadiman',
          'gabasawa',
          'Baki Yawa',
          'Dandagora',
          'Galadiman Arewa',
          'Ajiwa',
          'Dustin Safe',
          'Galadiman Kudu',
          'Gwado',
          'Jino',
          'Kayauki',
          'Madaji madu',
          'Modoji',
          'Shinkafi',
        ],
      },
      {
        lga: 'Kurfi',
        cities: [
          'Birchi',
          'Kurfi',
          'Barkiya',
          'Rawayau',
          'Tsauri',
          'Wurma',
          'Gwanzo',
          'Kufan Agga',
          'Kware',
          'Tamu',
          'Tamawa',
        ],
      },
      {
        lga: 'Kusada',
        cities: [
          'Kusada',
          'Kofa',
          'Dudunni',
          'Yashe',
          'Kusada',
          'Bauranya',
          'Aganta',
          'Baurawa',
          'Dangamau',
          'Kai-Kai',
          'Magama',
          'Gidan',
          'Mutun Daya',
          'Mairana',
          'Mawashi',
          'Tufani',
        ],
      },
      {
        lga: "Mai'Adua",
        cities: [
          "Mai'Adua",
          'Koza',
          "Mai'Koni",
          'Natsalle',
          'Saitawa',
          'Makerawa',
          'Kwadage',
          'Galadimawa',
          'Baida',
          'Buduma',
          'Bula',
          'Daba',
          'Dadin Sarki',
          'Dagon Hawa',
          'Dagura',
          'Dan Nasara',
          'Kurchi',
        ],
      },
      {
        lga: 'Malumfashi',
        cities: [
          'Malumfashi',
          'Yarmama',
          'Yaba',
          'Rawan Sanyi',
          'Na-Alma',
          'Dayi',
          'Birin Dawa',
          'Dansarai',
          'Gorar Dansaka',
          'Agagiwa',
          'Allah Madagara',
          'Almakiyayi',
          'Yaro',
        ],
      },
      {
        lga: 'Mani',
        cities: [
          'Mani',
          'Bagiwa',
          'Kwotta',
          'Machika',
          'Muduru',
          'Jani',
          'Bujawa',
          'Gewayau',
          'Aliyaba',
          'Bakan Karo',
          'Birjiwa',
          'Dawan Makawu',
          'Duwan',
          'Gajema',
          'Hancheta',
        ],
      },
      {
        lga: 'Mashi',
        cities: [
          'Mashi',
          'Karau',
          'Sonkaya',
          'Tamilo',
          'Agalla',
          'Badauri',
          'Bamle',
          'Birnin Kuka',
          'Dindiyel',
          'Dokawa',
          'Karawa',
          'Majigiri',
          'Mashi',
          'Shargalle',
          'Saye',
          'Gallu',
        ],
      },
      {
        lga: 'Matazuu',
        cities: [
          'Sayaya',
          'Matazu',
          'Mazoji',
          'Kogari',
          'Karaduwa',
          'Gwarjo',
          'Dissii',
          'Dan Kwari',
          'Gidan Dangata',
          'Gidan Karo',
          'Jataka',
          'Gyazawa',
          'Jumawa',
          'Karmatako',
          'Rinjin Gora',
          'Rinjin Idi',
        ],
      },
      {
        lga: 'Musawa',
        cities: [
          'Musawa',
          'Dangani',
          'Danjanku',
          'Karachi',
          'Gingin',
          'Tuge',
          'Yaradau',
          'Tabanni',
          'Kurkujan',
          'Kira',
          'Aljawa',
          'Daminawa',
          'Dan Kado',
          'Farin Dutse',
          'Filalawa',
          'Garu',
        ],
      },
      {
        lga: 'Rimi',
        cities: [
          'Rimi',
          'Sabon Garin',
          'Iyatawa',
          'Kurabau',
          'Masabo',
          'Makurda',
          'Remawa',
          'Majengobir',
          'Kadandani',
          'Fardami',
          'Abukur',
          'Allaraini',
          'Bardayya',
          'Bujawa',
          'Dan Musa',
        ],
      },
      {
        lga: 'Sabuwa',
        cities: [
          'Sabuna',
          'Sayau',
          'Damari',
          "Dugun Mu'Azu",
          'Gamji',
          'Machika',
          'Rafin Iwa',
          'Maibbako',
          'Albasa',
          'Awala',
          'Doka',
          'Gazari',
          'Ginanna',
          'Gobirawa',
          'Hayin Issau',
          'Kabalawa',
          'Katsalle',
          'Mazare',
          'Rumada',
        ],
      },
      {
        lga: 'Safana',
        cities: [
          'Safana',
          'Zakka',
          'Runka',
          'Baure',
          'Tsaskiya',
          'B/Dahu',
          'Bare-Bari',
          'Baude',
          'Dabbana Duhu',
          'Dan Jukku',
          'Dan Magaya',
          'Gora',
          'Guzarawa',
          'Illela',
          'Kunamawa',
          'Maikada',
          'Mammadau',
          'Moniya',
          'Unadau',
        ],
      },
      {
        lga: 'Sandamu',
        cities: [
          'Sandamu',
          'Danji',
          'Rade',
          'Sansamu',
          'Katsayal',
          'Karkarku',
          'Kwasarawa',
          'Dadin Kowa',
          'Rijiyar Tsamiya',
          'Ruma',
          'Damagi Yan Manuwa',
          'Duku Duku',
          'Fago',
          'Gazori',
          'Ingawa',
          'Jar Kuka',
          'Jiba',
          'Kaibaki',
        ],
      },
      {
        lga: 'Zango',
        cities: [
          'Zango',
          'Yardaje',
          'Sara',
          'Dargage',
          'Garni',
          'Gwamba',
          'Kanda',
          'Kawarin Kudi',
          'Ragogo Cidari',
          'Molawamai Madaka',
        ],
      },
    ],
  },
  southeast: {
    abia: [
      {
        lga: 'Aba North',
        cities: [
          'Eziama',
          'Ogbo',
          'Osusu',
          'Umuokoji',
          'Umuola-Egbule',
          'Umuola-Okpulor',
          'Uratta',
        ],
      },
      {
        lga: 'Aba South',
        cities: [
          'Abaukwu',
          'Amanfuru',
          'Ariaria',
          'Asaeme',
          'Asaokpuja',
          'Ihieorji',
          'Ndiegori',
          'Nnetu',
          'Ohabiam',
          'Umuagbai',
          'Umumb',
          'Umuosi',
        ],
      },
      {
        lga: 'Arochukwu',
        cities: [
          'Amasu',
          'Amoba',
          'Amuze',
          'Arochukwu',
          'Ibom',
          'Obinkita',
          'Oro',
          'Ujari',
        ],
      },
      {
        lga: 'Bende',
        cities: [
          'Alayi',
          'Bende',
          'Humbauzo',
          'Igbere',
          'Itumbauzo',
          'Nkpa',
          'Ozuitem',
          'Ugwueke',
          'Umu-Menyi',
          'Umuhu-Ezexhi',
          'Uzuakoli',
        ],
      },
      {
        lga: 'Ikwuano',
        cities: [
          'Ariam',
          'Ibeku',
          'Ibere',
          'Ikwuano',
          'Omuegwu',
          'Umuhu',
          'Umuokpara',
          'Usok',
        ],
      },
      {
        lga: 'Isiala-Ngwa North',
        cities: [
          'Ama-Asa',
          'Amapu-Ntigha',
          'Amasa-Ntigha',
          'Okpuala-Ngwa',
          'Ngwa Ukwu',
        ],
      },
      {
        lga: 'Isiala-Ngwa South',
        cities: [
          'Ahana',
          'Amaise',
          'Amaise-Ahoba',
          'Isiala-Nvosi',
          'Mbutu',
          'Ngwa',
          'Okporo',
          'Omoba',
          'Osokwa-Nvosi',
          'Ovu-Ngwa',
        ],
      },
      {
        lga: 'Isuikwato',
        cities: [
          'Achara-Ut',
          'Ezere',
          'Imenyi',
          'Isu-Amawu',
          'Mgbaugwu',
          'Ogudo- Asa',
          'Ohaise',
          'Umun-Nekwu',
        ],
      },
      { lga: 'Ngwa', cities: ['Ngwa'] },
      {
        lga: 'Obi Ngwa',
        cities: [
          'Abayi',
          'Ahiaba',
          'Akuma-Imo',
          'Ibeme',
          'Mgboko',
          'Mgboko-Amiri',
          'Mgboko-Otu Ngwa',
          'Ntiagha-Uzor',
          'Onuma',
        ],
      },
      {
        lga: 'Ohafia',
        cities: [
          'Ama-Asato',
          'Amangwu-Ohafia',
          'Amasa',
          'Aro-Ngwa',
          'Aso-Akwa',
          'Ebem-Ohafia',
          'Nkporo',
          'Ohofor-Ohafia',
          'Oko-Aku',
          'Oma-Ohafia',
        ],
      },
      {
        lga: 'Osisioma',
        cities: [
          'Amaitoli',
          'Amasa',
          'Aro-Ngwa',
          'Okpu-Umuobo',
          'Osisioma',
          'Oso-Okwa',
          'Umunneise',
          'Uratta',
        ],
      },
      {
        lga: 'Ugwunagbo',
        cities: [
          'Abayi',
          'Akanu',
          'Alaoji',
          'Amaokpu-Umuitiri',
          'Obuzor',
          'Osusu-Aku',
          'Ozaa-Umuebukwu',
          'Ugwunagbo',
          'Uke',
        ],
      },
      {
        lga: 'Ukwa East',
        cities: [
          'Akwete',
          'Ala-Ukwu',
          'Azumini',
          'Ibeme',
          'Ikwueke',
          'Ikwuo-Rieator',
          'Ntigha-uzo',
          'Obohia',
          'Umuigbube-Achara',
        ],
      },
      {
        lga: 'Ukwa West',
        cities: ['Asa-North', 'Obokwe', 'Oke-Ikpe', 'Ozar-Ukwu', 'Ozar-West'],
      },
      {
        lga: 'Umuahia North',
        cities: ['Ndume', 'Ohokobe', 'Ossa', 'Ugwunihara'],
      },
      {
        lga: 'Umuahia South',
        cities: [
          'Ahiaukwa',
          'Amakama',
          'Apumiri',
          'Nsirimo',
          'Ohiaocha',
          'Old Umuahia',
          'Omaegwu',
          'Ubalaka',
        ],
      },
      {
        lga: 'Umu-Nneochi',
        cities: ['Achara', 'Lomara', 'Nkwo-Agu', 'Umuelem'],
      },
    ],
    ebonyi: [
      {
        lga: 'Afikpo South',
        cities: [
          'Nguzu Edda',
          'Owutu-Edda',
          'Ebuwana-Edda',
          'Etiti-Edda',
          'Amangwu-Edda',
          'Oso-Edda',
          'Ogbu-Egbu',
        ],
      },
      {
        lga: 'Afikpo North',
        cities: ['Afikpo', 'Ohaisu', 'Itim', 'Nkpoghoro', 'Ugwuegbu', 'Amaizu'],
      },
      {
        lga: 'Onicha',
        cities: ['Isu', 'Oshiri', 'Abaomega', 'Onicha-Igbeza', 'Ukawu', 'Isu'],
      },
      {
        lga: 'Ohaozara',
        cities: [
          'Obiozara Uburu',
          'Uburu',
          'Ugwu-Langwu',
          'Ishiagu',
          'Okposi',
          'Akaeze',
        ],
      },
      {
        lga: 'Abakaliki',
        cities: ['Nkaliki', 'Abakpa', 'Amachi', 'Amagu', 'Amagu Unuhu'],
      },
      {
        lga: 'Ishielu',
        cities: [
          'Ezillo',
          'Azuinyoba',
          'Nkalaha',
          'Nkolagu',
          'Iyonu',
          'Ntezi',
          'Okpoto',
          'Agba',
          'Ezzagu',
          'Emuhu',
          'Emuhu-Ali',
          'Amazu',
          'Agge-Egde',
          'Ebeagu',
        ],
      },
      {
        lga: 'Ikwo',
        cities: [
          'Achara',
          'Ndufu-Alike',
          'Ndufu-Achara',
          'Eka-Awoke',
          'Ndiagu Achara',
          'Akpan-Wudele',
          'Igbudu',
          'Ndiagu.Amagu',
          'Ndufu-Amagu',
          'Etim-Ekpuitumo',
          'Edua-Alike',
          'Enyibichiri-Alike',
          'Agge-Egde',
          'Inyimagu',
        ],
      },
      {
        lga: 'Ezza North',
        cities: [
          'Ebiaji',
          'Amagu',
          'Amawula',
          'Achara-Ezza',
          'Amana',
          'Amazu',
          'Ameka',
          'Amuda',
          'Amuda-Ekka',
        ],
      },
      {
        lga: 'Ohaukwu',
        cities: [
          'Ezzamgbo',
          'Umuezeoka-Ogbo',
          'Umuogudu-Oshia',
          'Amoffia',
          'Ngbo',
          'Okposi-Eheku',
          'Umugudu',
          'Okposhi-Ngbo',
          'Ekwashi-Ngbo',
          'Ukwuagba-Ngbo',
          'Effium',
        ],
      },
      {
        lga: 'Ebonyi',
        cities: [
          'Ugbodo',
          'Amadi',
          'Nkoleke-Achara',
          'Izzi Unuhu',
          'Nkaleke-Achara',
          'Okpui-Tumo',
          'Edda',
          'Amagu',
          'Ishieke',
        ],
      },
      {
        lga: 'Ivo',
        cities: [
          'Isiako',
          'Ishiagu',
          'Akaeze Ukwu',
          'Amagu',
          'Amonye',
          'Ihenta',
          'Ogidi',
          'Iyioji',
          'Akaeze',
          'Ndiokoro Ukwu',
          'Ngwogwo',
          'Obinagu',
          'Okue',
          'Umobo',
          'Agbaja',
          'Anyanwuigwe',
        ],
      },
    ],
    enugu: [
      {
        lga: 'Enugu South',
        cities: [
          'Uwani',
          'Akwuke',
          'Amechi',
          'Ugwuaji',
          'Obeagu',
          'Awkunanaw',
          'Amechi-Uwani',
        ],
      },
      {
        lga: 'Igbo-Eze South',
        cities: [
          'Ibakwa-Aka',
          'Uhunowerre',
          'Alor',
          'Iheakpu',
          'Awka',
          'Ovoko',
          'Uhunowerre',
        ],
      },
      {
        lga: 'Enugu North',
        cities: ['Enugu', 'Amaigbo Lane', 'Onuato', 'Umunevo', 'Ihenwuzi'],
      },
      {
        lga: 'Nkanu East',
        cities: [
          'Amagunze',
          'Ihuopkara',
          'Akpawfu(Akpofu)',
          'Amagunze',
          'Amauzam',
          'Owo',
          'Amechi-Idodo',
          'Nara',
          'Nkerefi',
          'Nomeh',
          'Ogbahu',
          'Oruku',
          'Ugbawka',
        ],
      },
      {
        lga: 'Udi Agwu',
        cities: [
          'Udi',
          'Appakwume-Nze',
          'Okpatu',
          'Affa',
          'Eke',
          'Ebe',
          'Ngwo-Asa',
          'Ngwo-Uno',
          'Obioma',
          'Abia',
          'Amokwe',
        ],
      },
      {
        lga: 'Oji-River',
        cities: [
          'Ugwuoba',
          'Inyi',
          'Akpugo-Eze',
          'Achi-Uno',
          'Oji-River(Urban)',
          'Awlaw',
        ],
      },
      {
        lga: 'Ezeagu',
        cities: [
          'Aguobuowa',
          'Olo',
          'Iwollo-Oghe',
          'Umana',
          'Ndiagu',
          'Aguobu-Umu',
        ],
      },
      {
        lga: 'IgboEze North',
        cities: ['Enugu-Ezike', 'Etteh', 'Umuozzi', 'Ezzodo', 'Esodo'],
      },
      {
        lga: 'Isi-Uzo',
        cities: ['Ikem', 'Umualor', 'Eha-Amufu', 'Neke', 'Mbu', 'Ikem'],
      },
      {
        lga: 'Nsukka',
        cities: [
          'Nsukka',
          'Ede-Oballa',
          'Ehaa-Alumona',
          'Okpuje',
          'Opi-Agu',
          'Edem',
          'Umuabor',
          'Opi',
          'Opi-Agu',
          'Okpaligbo',
          'Okutu',
          'Opkuje',
          'Obukpa',
          'Ibagwani',
        ],
      },
      {
        lga: 'Igbo-Ekiti',
        cities: [
          'Ogbede',
          'Diogbe',
          'Aku',
          'Ohodo',
          'Ukehe',
          'Umuna',
          'Umunko',
          'Ekwegbe',
          'Ozalla',
          'Ochima',
          'Ikolo',
          'Idume',
          'Ohebedim',
        ],
      },
      {
        lga: 'Uzo-Uwani',
        cities: [
          'Umulokpa',
          'Adaba',
          'Umulokpa',
          'Ojor',
          'Igga',
          'Adani',
          'Uvuru',
          'Nimbo',
        ],
      },
      {
        lga: 'Enugu East',
        cities: [
          'Nike-Uno',
          'Ugwogo',
          'Mbuli',
          'Njodo',
          'Agbogazi',
          'Ako',
          'Akpoga',
          'Alulu',
        ],
      },
      {
        lga: 'Aninri',
        cities: ['Ndiagbor', 'Mpu', 'Ndiagbor', 'Nnenwe', 'Oduma', 'Opkanku'],
      },
      {
        lga: 'Nkanu East',
        cities: [
          'Amagunze',
          'Ihuopkara',
          'Akpawfu(Akpofu)',
          'Amauzam',
          'Owo',
          'Amechi-Idodo',
          'Nara',
          'Nkerefi',
          'Nomeh',
          'Ogbahu',
          'Oruku',
          'Ugbawka',
        ],
      },
      {
        lga: 'Udenu',
        cities: [
          'Obollo-Afor',
          'Ezima-Uno',
          'Obollo-Afor',
          'Ezima-Agu',
          'Amolla',
          'Igugu',
          'Umundu Orba',
          'Agbodu',
          'Aba',
          'Obollo-Etiti',
          'Obollo-Eke',
          'Imilike-Uno',
          'Imilike-Agu',
        ],
      },
    ],
    imo: [
      {
        lga: 'Aboh-Mbaise',
        cities: [
          'Afor Oru',
          'Oru-Ahiara',
          'Ogbe',
          'Lude/Nnara-Mbia',
          'Obodo-Ahiara',
          'Ekwere-Azu',
          'Obohia',
          'Umuokirika',
          'Obodo-Ujichi',
          'Ogwuama/Amazi',
          'Akobor',
          'Nkpam',
        ],
      },
      {
        lga: 'Ehime-Mbano',
        cities: ['Umuezeala', 'Agbaje', 'Umueze', 'Umukobia', 'Nneoto'],
      },
      {
        lga: 'Ezinihitte',
        cities: [
          'Itu',
          'Amumara',
          'Akpodim',
          'Azuzuahia-Eziudo',
          'Owagia-Eziudo',
          'Ife',
          'Obizi',
          'Onicha',
          'Udo',
        ],
      },
      {
        lga: 'Ideato North',
        cities: [
          'Urualla',
          'Akpullu',
          'Umualaoma',
          'Osina',
          'Isiokpo',
          'Akokwa',
          'Uzii',
        ],
      },
      {
        lga: 'Ideato South',
        cities: [
          'Dikenafai',
          'Ntueke',
          'Umuchima',
          'Ubiohia',
          'Umuobom',
          'Umueshi',
          'Umuakam/Umuago',
        ],
      },
      {
        lga: 'Ihitte/Uboma',
        cities: [
          'Isinweke',
          'Amakoha',
          'Umuezegwu',
          'Ato-Werem',
          'Abuke',
          'Umuoma',
          'Amainyi',
          'Amuchinumo',
          'Umuihi',
          'Ezimba',
          'Onichi-Uboma',
        ],
      },
      {
        lga: 'Ikeduru',
        cities: [
          'Iho',
          'Abasu',
          'Akabo',
          'Amaimo',
          'Amakohia',
          'Amatta',
          'Atta',
          'Avuvu',
          'Ezima',
          'Owu-Binubi',
        ],
      },
      {
        lga: 'Isiala Mbano',
        cities: [
          'Umuelemai',
          'Umuduru',
          'Osu-Owerre',
          'Asu-Ama',
          'Umosu',
          'Amausari',
          'Amaraku',
          'Obollo',
          'Umunkwo',
          'Ogbor',
          'Uguri',
          'Ibeme',
          'Oka',
        ],
      },
      {
        lga: 'Isu',
        cities: [
          'Umundugba',
          'Amadugba',
          'Ekwe',
          'Amurie-Amanze',
          'Isunjaba',
          'Uburu Ekwe',
          'Oboro-Amurie',
        ],
      },
      {
        lga: 'Mbaitoli',
        cities: [
          'Nworieubi',
          'Eziama Obiato',
          'Umunoha',
          'Orodo',
          'Afara',
          'Ogwa',
        ],
      },
      {
        lga: 'Ngor-Okpala',
        cities: [
          'Umuneke Ngor',
          'Nguru',
          'Umuowa',
          'Umukabia Ngor',
          'Ntu',
          'Alulu',
          'Oburu',
          'Obokwe',
          'Alatia',
        ],
      },
      {
        lga: 'Njaba',
        cities: ['Nnenasa', 'Umuaka', 'Okwudor', 'Amucha', 'Attah'],
      },
      {
        lga: 'Nwangele',
        cities: ['Amaigbo', 'Abbe', 'Isu', 'Umuozu', 'Abajah'],
      },
      {
        lga: 'Nkwerre',
        cities: [
          'Nkwerre',
          'Owerre-Nkworji',
          'Eziama Obaire',
          'Amaokpara',
          'Umudi',
          'Umuezeanoruo',
          'Umunwala',
        ],
      },
      {
        lga: 'Obowo',
        cities: [
          'Otoko',
          'Avutu',
          'Ehume',
          'Umuariam/Achara',
          'Alike Obowo',
          'Amuzi-Obowo',
          'Ikwuato',
          'Umunachi',
          'Umuokeh',
          'Umuosochie',
          'Umungwa',
        ],
      },
      {
        lga: 'Oguta',
        cities: [
          'Oguta',
          'Agwa',
          'Orsu Obodo',
          'Egwe',
          'Nnebukwu',
          'Egbuoma',
          'Awa',
          'Akabor',
          'Mbgelle',
          'Ezi Orsu',
          'Nkwesi',
          'Izonbe',
        ],
      },
      {
        lga: 'Ohaji/Egbema',
        cities: [
          'Mmahu-Egbema',
          'Nwari-Agwa',
          'Egbema',
          'Ohoba',
          'Assa',
          'Obile',
          'Umuokanne',
          'Awara-Ikwerede',
          'Mgbirichi',
          'Umuopu',
        ],
      },
      {
        lga: 'Okigwe',
        cities: ['Okigwe', 'Otanzu', 'Amuro', 'Umulolo', 'Ihube', 'Otan-Chara'],
      },
      {
        lga: 'Orlu',
        cities: [
          'Orlu',
          'Umuzike',
          'Umuoma',
          'Umutanze',
          'Umuna',
          'Umudioka',
          'Okporo',
          'Ogberuru',
          'Obibi-Och',
          'Mgbee',
          'Ihitte-Owerre',
          'Ihioma',
          'Ebe',
          'Eziachi',
          'Amaifeke',
          'Amaike',
        ],
      },
      {
        lga: 'Orsu',
        cities: [
          'Awo-Idemili',
          'Amaruru',
          'Assa-Ubirielem',
          'Ebenator',
          'Eziawa',
          'Ihitte-Nasa',
          'Ihitte-Ukwu',
          'Umuhu-Okaiba',
        ],
      },
      {
        lga: 'Oru East',
        cities: [
          'Omuma',
          'Akatta',
          'Akuma/Amagu',
          'Amiri',
          'Ofekatai',
          'Omuma',
          'Eziawo',
          'Awo-Omama',
        ],
      },
      {
        lga: 'Oru West',
        cities: [
          'Mgbidi',
          'Amaofuo',
          'Eleh',
          'Aji',
          'Ibi Asoebe',
          'Nempi Otulu',
          'Ohakpu',
          'Ubulu',
          'Ozara',
        ],
      },
      {
        lga: 'Owerri-Municipal',
        cities: ['Owerri', 'New Owerri'],
      },
      {
        lga: 'Owerri North',
        cities: [
          'Uratta',
          'Egbu',
          'Ulakwo',
          'Emekuku',
          'Emii',
          'Agbala',
          'Naze',
          'Awaka',
          'Azaraubo',
          'Amakohia',
          'Uratta',
          'Ezimba',
          'Orji',
        ],
      },
      {
        lga: 'Owerri West',
        cities: [
          'Umuguma',
          'Avu',
          'Nekede',
          'Ihiagwa',
          'Obinze',
          'Umunwoha',
          'Okukuv(Obogwu)',
          'Okolochi',
          'Eziobodo',
          'Oforola',
        ],
      },
    ],
  },
  southsouth: {
    crossRiver: [
      {
        lga: 'Akpabuyo',
        cities: [
          'Ikot Nakanda',
          'Atimbo',
          'Eneyo',
          'Ikang',
          'Idundu',
          'Ikot Edem Odo',
          'Ikot Eyo',
        ],
      },
      {
        lga: 'Akamkpa',
        cities: [
          'Akamkpa',
          'Egup-Ipa',
          'Ehom',
          'Erei',
          'Iko Ekpe-Rem',
          'Ikpai',
          'Netin',
          'Ito',
          'Oban',
          'Ojuk',
          'Ubang-Hara',
          'Umon',
          'Uyanga',
        ],
      },
      {
        lga: 'Biase',
        cities: [
          'Akpet Central',
          'Abanwan',
          'Afono',
          'Edu/Elu',
          'Egbor',
          'Etana',
          'Ipene',
          'Ipine',
          'Ibini',
          'Obum',
          'Umolor',
          'Urugbam',
        ],
      },
      {
        lga: 'Abi',
        cities: [
          'Itigidi',
          'Adadama',
          'Afafanyi',
          'Igonigoni',
          'Ekureku',
          'Imabana',
          'Usumutong',
          'Ubuego',
          'Itigidi',
          'Ebom',
          'Ediba/Anong',
        ],
      },
      {
        lga: 'Ikom',
        cities: [
          'Ikom',
          'Abakpa',
          'Bisiri',
          'Bojor Achibong',
          'Obudu',
          'Oguja',
          'Okim Osabor',
          'Okuku',
        ],
      },
      {
        lga: 'Yarkur',
        cities: [
          'Ugep',
          'Abanakpai',
          'Afrekpe',
          'Ajere',
          'Assiga',
          'Biko Biko',
          'Idomi',
          'Ijiman',
          'Ijom',
          'Ikpakapit',
          'Inyima',
          'Mkpani',
          'Nkpolo',
          'Ntan',
        ],
      },
      {
        lga: 'Obubra',
        cities: [
          'Obubra',
          'Iyalla',
          'Ofat(Adum)',
          'Ofodua(Adum)',
          'Ofombo-Ngha',
          'Okom',
          'Osopong',
        ],
      },
      {
        lga: 'Boki',
        cities: [
          'Boje',
          'Abawyum',
          'Akpara-Bong',
          'Ikom Rural',
          'Nde',
          'Nte',
          'Ofutop',
          'Osokom',
          'Etung',
        ],
      },
      {
        lga: 'Ogoja',
        cities: ['Ogoja', 'Ekajuk', 'Mbube', 'Nkum Iborr', 'Nkum Irede'],
      },
      {
        lga: 'Yala',
        cities: [
          'Okpoma',
          'Yahe',
          'Ugaga',
          'Ijegu',
          'Oloko',
          'Imaje',
          'Oke',
          'Echumoga',
          'Woda',
          'Ebo',
          'Igede Edii',
          'Itekpa',
          'Maa',
          'Wonye',
          'Uchu',
          'Osina',
        ],
      },
      {
        lga: 'Obanliku',
        cities: [
          'Sankwala',
          'Basang',
          'Bebi',
          'Becheve',
          'Bendi',
          'Bishiri',
          'Busi',
          'Bisu',
          'Utanga',
        ],
      },
      {
        lga: 'Obudu',
        cities: [
          'Obudu',
          'Alege',
          'Becheve',
          'Bettee',
          'Oban-Liku',
          'Okpe',
          'South Oban-Liku',
          'Ugang',
          'Unpe',
          'Utanga',
          'Utygwang',
        ],
      },
      {
        lga: 'Calabar South',
        cities: ['Anantigha'],
      },
      {
        lga: 'Etung',
        cities: [
          'Effraya',
          'Abia',
          'Abijang',
          'Agbokim',
          'Ajassor',
          'Bendeghe',
          'Ekiem',
          'Effraya',
          'Etomi',
          'Itaka',
          'Mkpot/Ayuk Aba',
          'Nsofang',
        ],
      },
      {
        lga: 'Bekwara',
        cities: [
          'Abuochiche',
          'Afrike',
          'Yala',
          'Ejajuk',
          'Gabu',
          'Gakem',
          'Mbube',
          'Nkum',
          'Ukele',
          'Ogoja Urban',
          'Western Yala Ya',
          'Yache',
        ],
      },
      {
        lga: 'Bakassi',
        cities: [
          'Ikang',
          'Abana',
          'Akpankanya',
          'Akwa',
          'Amoto',
          'Ambai Ekpa',
          'Archibong',
          'Atai',
          'Ema',
          'Efut Iwang',
          'Ekpot Abia',
          'Odiong',
        ],
      },
    ],
    delta: [
      {
        lga: 'Oshimili',
        cities: [
          'Asaba',
          'Abraka',
          'Burutu',
          'Koko',
          'Oghara',
          'Okuokoko',
          'Ovwian',
          'Sapele',
          'Warri',
          'Agbor',
          'Effurun',
          'Kwale',
          'Ogwashi Ukwu',
          'Oleh',
          'Ozoro',
          'Ughelli',
        ],
      },
      {
        lga: 'Aniocha South',
        cities: [
          'Asaba',
          'Abraka',
          'Burutu',
          'koko',
          'Oghara',
          'Okuokoko',
          'Ovwian',
          'Sapele',
          'Warri',
          'Agbo',
          'Effurun',
          'Kwale',
          'Ogwashi Ukwu',
          'Oleh',
          'Ozoro',
          'Ughelli',
        ],
      },
      {
        lga: 'Ika South',
        cities: [
          'Asaba',
          'Abraka',
          'Burutu',
          'koko',
          'Oghara',
          'Okuokoko',
          'Ovwian',
          'Sapele',
          'Warri',
          'Agbo',
          'Effurun',
          'Kwale',
          'Ogwashi Ukwu',
          'Oleh',
          'Ozoro',
          'Ughelli',
        ],
      },
      {
        lga: 'Ika North-East',
        cities: [
          'Asaba',
          'Abraka',
          'Burutu',
          'koko',
          'Oghara',
          'Okuokoko',
          'Ovwian',
          'Sapele',
          'Warri',
          'Agbo',
          'Effurun',
          'Kwale',
          'Ogwashi Ukwu',
          'Oleh',
          'Ozoro',
          'Ughelli',
        ],
      },
      {
        lga: 'Ndokwa West',
        cities: [
          'Asaba',
          'Abraka',
          'Burutu',
          'koko',
          'Oghara',
          'Okuokoko',
          'Ovwian',
          'Sapele',
          'Warri',
          'Agbo',
          'Effurun',
          'Kwale',
          'Ogwashi Ukwu',
          'Oleh',
          'Ozoro',
          'Ughelli',
        ],
      },
      {
        lga: 'Ndokwa East',
        cities: [
          'Asaba',
          'Abraka',
          'Burutu',
          'koko',
          'Oghara',
          'Okuokoko',
          'Ovwian',
          'Sapele',
          'Warri',
          'Agbo',
          'Effurun',
          'Kwale',
          'Ogwashi Ukwu',
          'Oleh',
          'Ozoro',
          'Ughelli',
        ],
      },
      {
        lga: 'Isoko South',
        cities: [
          'Asaba',
          'Abraka',
          'Burutu',
          'koko',
          'Oghara',
          'Okuokoko',
          'Ovwian',
          'Sapele',
          'Warri',
          'Agbo',
          'Effurun',
          'Kwale',
          'Ogwashi Ukwu',
          'Oleh',
          'Ozoro',
          'Ughelli',
        ],
      },
      {
        lga: 'Isoko North',
        cities: [
          'Asaba',
          'Abraka',
          'Burutu',
          'koko',
          'Oghara',
          'Okuokoko',
          'Ovwian',
          'Sapele',
          'Warri',
          'Agbo',
          'Effurun',
          'Kwale',
          'Ogwashi Ukwu',
          'Oleh',
          'Ozoro',
          'Ughelli',
        ],
      },
      {
        lga: 'Bomadi',
        cities: [
          'Asaba',
          'Abraka',
          'Burutu',
          'koko',
          'Oghara',
          'Okuokoko',
          'Ovwian',
          'Sapele',
          'Warri',
          'Agbo',
          'Effurun',
          'Kwale',
          'Ogwashi Ukwu',
          'Oleh',
          'Ozoro',
          'Ughelli',
        ],
      },
      {
        lga: 'Burutu',
        cities: [
          'Asaba',
          'Abraka',
          'Burutu',
          'koko',
          'Oghara',
          'Okuokoko',
          'Ovwian',
          'Sapele',
          'Warri',
          'Agbo',
          'Effurun',
          'Kwale',
          'Ogwashi Ukwu',
          'Oleh',
          'Ozoro',
          'Ughelli',
        ],
      },
      {
        lga: 'Ughelli South',
        cities: [
          'Asaba',
          'Abraka',
          'Burutu',
          'koko',
          'Oghara',
          'Okuokoko',
          'Ovwian',
          'Sapele',
          'Warri',
          'Agbo',
          'Effurun',
          'Kwale',
          'Ogwashi Ukwu',
          'Oleh',
          'Ozoro',
          'Ughelli',
        ],
      },
      {
        lga: 'Ughelli North',
        cities: [
          'Asaba',
          'Abraka',
          'Burutu',
          'koko',
          'Oghara',
          'Okuokoko',
          'Ovwian',
          'Sapele',
          'Warri',
          'Agbo',
          'Effurun',
          'Kwale',
          'Ogwashi Ukwu',
          'Oleh',
          'Ozoro',
          'Ughelli',
        ],
      },
      {
        lga: 'Ethiope West',
        cities: [
          'Asaba',
          'Abraka',
          'Burutu',
          'koko',
          'Oghara',
          'Okuokoko',
          'Ovwian',
          'Sapele',
          'Warri',
          'Agbo',
          'Effurun',
          'Kwale',
          'Ogwashi Ukwu',
          'Oleh',
          'Ozoro',
          'Ughelli',
        ],
      },
      {
        lga: 'Ethiope East',
        cities: [
          'Asaba',
          'Abraka',
          'Burutu',
          'koko',
          'Oghara',
          'Okuokoko',
          'Ovwian',
          'Sapele',
          'Warri',
          'Agbo',
          'Effurun',
          'Kwale',
          'Ogwashi Ukwu',
          'Oleh',
          'Ozoro',
          'Ughelli',
        ],
      },
      {
        lga: 'Sapele',
        cities: [
          'Asaba',
          'Abraka',
          'Burutu',
          'koko',
          'Oghara',
          'Okuokoko',
          'Ovwian',
          'Sapele',
          'Warri',
          'Agbo',
          'Effurun',
          'Kwale',
          'Ogwashi Ukwu',
          'Oleh',
          'Ozoro',
          'Ughelli',
        ],
      },
      {
        lga: 'Okpe',
        cities: [
          'Asaba',
          'Abraka',
          'Burutu',
          'koko',
          'Oghara',
          'Okuokoko',
          'Ovwian',
          'Sapele',
          'Warri',
          'Agbo',
          'Effurun',
          'Kwale',
          'Ogwashi Ukwu',
          'Oleh',
          'Ozoro',
          'Ughelli',
        ],
      },
      {
        lga: 'Warri North',
        cities: [
          'Asaba',
          'Abraka',
          'Burutu',
          'koko',
          'Oghara',
          'Okuokoko',
          'Ovwian',
          'Sapele',
          'Warri',
          'Agbo',
          'Effurun',
          'Kwale',
          'Ogwashi Ukwu',
          'Oleh',
          'Ozoro',
          'Ughelli',
        ],
      },
      {
        lga: 'Warri South',
        cities: [
          'Asaba',
          'Abraka',
          'Burutu',
          'koko',
          'Oghara',
          'Okuokoko',
          'Ovwian',
          'Sapele',
          'Warri',
          'Agbo',
          'Effurun',
          'Kwale',
          'Ogwashi Ukwu',
          'Oleh',
          'Ozoro',
          'Ughelli',
        ],
      },
      {
        lga: 'Uvwie',
        cities: [
          'Asaba',
          'Abraka',
          'Burutu',
          'koko',
          'Oghara',
          'Okuokoko',
          'Ovwian',
          'Sapele',
          'Warri',
          'Agbo',
          'Effurun',
          'Kwale',
          'Ogwashi Ukwu',
          'Oleh',
          'Ozoro',
          'Ughelli',
        ],
      },
      {
        lga: 'Udu',
        cities: [
          'Asaba',
          'Abraka',
          'Burutu',
          'koko',
          'Oghara',
          'Okuokoko',
          'Ovwian',
          'Sapele',
          'Warri',
          'Agbo',
          'Effurun',
          'Kwale',
          'Ogwashi Ukwu',
          'Oleh',
          'Ozoro',
          'Ughelli',
        ],
      },
      {
        lga: 'Warri Central',
        cities: [
          'Asaba',
          'Abraka',
          'Burutu',
          'koko',
          'Oghara',
          'Okuokoko',
          'Ovwian',
          'Sapele',
          'Warri',
          'Agbo',
          'Effurun',
          'Kwale',
          'Ogwashi Ukwu',
          'Oleh',
          'Ozoro',
          'Ughelli',
        ],
      },
      {
        lga: 'Ukwani',
        cities: [
          'Asaba',
          'Abraka',
          'Burutu',
          'koko',
          'Oghara',
          'Okuokoko',
          'Ovwian',
          'Sapele',
          'Warri',
          'Agbo',
          'Effurun',
          'Kwale',
          'Ogwashi Ukwu',
          'Oleh',
          'Ozoro',
          'Ughelli',
        ],
      },
      {
        lga: 'Oshimili North',
        cities: [
          'Asaba',
          'Abraka',
          'Burutu',
          'koko',
          'Oghara',
          'Okuokoko',
          'Ovwian',
          'Sapele',
          'Warri',
          'Agbo',
          'Effurun',
          'Kwale',
          'Ogwashi Ukwu',
          'Oleh',
          'Ozoro',
          'Ughelli',
        ],
      },
      {
        lga: 'Patani',
        cities: [
          'Asaba',
          'Abraka',
          'Burutu',
          'koko',
          'Oghara',
          'Okuokoko',
          'Ovwian',
          'Sapele',
          'Warri',
          'Agbo',
          'Effurun',
          'Kwale',
          'Ogwashi Ukwu',
          'Oleh',
          'Ozoro',
          'Ughelli',
        ],
      },
    ],
    edo: [
      {
        lga: 'Esan North-East',
        cities: ['Uromi', 'Edo Esan', 'Uzea'],
      },
      {
        lga: 'Esan West',
        cities: [
          'Ekpoma',
          'Eghoro',
          'Idio',
          'Naoka',
          'Ogwa',
          'Ujiogba',
          'Ukhun',
          'Urohi',
        ],
      },
      {
        lga: 'Akoko-Edo',
        cities: [
          'Igarra',
          'Akoko',
          'Ikpeshi-Egbegbere',
          'Atje',
          'Kakumo-Anyantan',
        ],
      },
      {
        lga: 'Egor',
        cities: [
          'Uselu',
          'Agidigbi',
          'Egor',
          'Environ Camp',
          'Iguediayi',
          'Iguikpe',
          'Oghedaivbiobaa',
          'Oghokhegbo',
          'Oviasuyi Camp',
          'gboko',
          'Ugbi',
        ],
      },
      {
        lga: 'Ikpoba',
        cities: [
          'Idogbo',
          'Aduwawa',
          'Agedo',
          'Ekiuwa',
          'Evbumufi',
          'Evbuomodu',
          'Ighekpe',
          'Iguehana',
          'Ogbeson',
          'Ohovbe',
          'Otenes Camp',
          'Urora',
          'Ute Okha',
          'Ajoki Akpes Camp',
          'Avbiama',
        ],
      },
      {
        lga: 'Esan Central',
        cities: [
          'Irrua',
          'Ewu',
          'Opoji',
          'Ugbegun',
          'Igueben',
          'Ebelle',
          'Ewossa',
        ],
      },
      {
        lga: 'Etsako Central',
        cities: ['Fugar', 'Ekperi', 'Fugar-Avianwu', 'Okpekpe', 'Okpella'],
      },
      {
        lga: 'Igueben',
        cities: ['Igueben', 'Amahor', 'Ekpon', 'Ugun Urban'],
      },
      {
        lga: 'Oredo',
        cities: [
          'Benin',
          'Gra',
          'Etete',
          'Ibiwe',
          'Iwegie',
          'Ugbague',
          'Ihogbe',
          'Isekhere',
          'Oreoghene',
          'Ibiwe',
          'Ikpema',
          'Eguadase',
          'New Binin',
          'Ogbe',
          'Ogbelaka',
        ],
      },
      {
        lga: 'Ovia South-West',
        cities: [
          'Iguoba-Zuwa',
          'Ofunama',
          'Ora',
          'Siluko',
          'Udo',
          'Ugbogue',
          'Umaza',
          'Usen',
        ],
      },
      {
        lga: 'Ovia North-West',
        cities: [
          'Okada',
          'Adolor',
          'Iguoshodin',
          'Isiuwa',
          'Kokhuo',
          'Oduna',
          'Ofunm-Wengbe',
          'Oghede',
          'Oluku',
          'Uhiere',
          'Utoka',
        ],
      },
      {
        lga: 'Orhionwon',
        cities: [
          'Abudu',
          'Aibiokunla',
          'Igbanke',
          'Oloten',
          'Ugboko',
          'Ugu',
          'Urho-Nigbe',
        ],
      },
      {
        lga: 'Uhunmwonde',
        cities: [
          'Ehor',
          'Egbede',
          'Igieduma',
          'Isi North',
          'Isi South',
          'Uhi',
          'Umagbae',
        ],
      },
      {
        lga: 'Etsako East',
        cities: [
          'Agenebode',
          'Agiere',
          'Anumeji',
          'Avhiodor',
          'Bode-Waterside',
          'Dapapa',
          'Edegbe',
          'Egori-Nauge',
        ],
      },
      {
        lga: 'Esan South-East',
        cities: [
          'Ubiaja',
          'Emu',
          'Equare-Ewatto',
          'Ewohimi',
          'Ilushi',
          'Inyenlen',
          'Ohordua',
          'Okhu-Essan',
          'Onog-Holo',
          'Oria',
        ],
      },
    ],
  },
  southwest: {
    ekiti: [
      {
        lga: 'Ado',
        cities: [
          'Ado Ekiti',
          'Ago Araromi',
          'Ajebamidele',
          'Amirin',
          'Aso Ayegbule',
          'Ategbedo',
          'Ernfun',
          'Igim Okogo',
          'Igirigiri',
          'Ika',
          'Ikewo',
          'ilokun',
          'Iranse',
        ],
      },
      {
        lga: 'Ekiti-East',
        cities: [
          'Omuo-Ekiti',
          'Ikun',
          'Araromi',
          'Eda',
          'Ile',
          'Isinbode',
          'Eremiji',
          'Igbole',
          'Suru',
          'Omuo Ekiti',
          'Ilasa',
          'Isinbode',
          'Oda-do',
        ],
      },
      {
        lga: 'Ekiti-West',
        cities: [
          'Aramoko',
          'Ido Ajinare',
          'Ikogosi',
          'Ipole',
          'Iloro',
          'Aramoko',
          'Erinijiyan',
          'Okemesi',
          'Isokowa',
          'Egede',
          'Orokuta',
          'Osemo',
          'Kajola',
        ],
      },
      {
        lga: 'Emure/Ise/Orun',
        cities: [
          'Emure',
          'Oke Emure',
          'Odo Emure',
          'Ideimudu',
          'Ogbontioro',
          'Sasere',
          'Owode',
          'Owosi',
          'Igboso',
          'Ilu',
          'Oge Oke',
          'Seri',
          'Oke Sett',
          'Omaje Opticum',
          'Ose',
          'Owos',
          'Agbanimu',
        ],
      },
      {
        lga: 'Ekiti South-West',
        cities: [
          'Ilawe',
          'Igbara Odo',
          'Ilawe I',
          'Ilawe II',
          'Ilawe III',
          'Ilawe IV',
          'Ilawe V',
          'Igbara Odo I',
          'Igbara Odo II',
        ],
      },
      {
        lga: 'Ikere',
        cities: [
          'Okejegbende',
          'Oniroba',
          'Okeruku',
          'Ugele/Aroku',
          'Aso-Osolo',
          'Atoba',
          'Aba Igbira',
          'Ugbo-Oje',
          'Ijao',
          'Odese',
          'Ogbonjana',
          'Oke-Osun',
          'Oyo',
          'Are Araromi',
          'Ugbo-Uro',
        ],
      },
      {
        lga: 'Irepodun',
        cities: [
          'Igede-Ekiti',
          'Iyin-Ekiti',
          'Igbemo-Ekiti',
          'Awo-Ekiti Afao',
          'Are',
          'Awo',
          'Igbemo',
          'Iropora',
          'Esure',
          'Eyio',
          'Iworoko',
        ],
      },
      {
        lga: 'Ijero',
        cities: [
          'Ijero',
          'Ekamarun',
          'Ikoro',
          'iloro',
          'Ijunrin',
          'Ipoti',
          'Odo',
          'Owa',
          'Idao',
          'Ilukuno',
          'Iroko',
          'Temidire',
          'Abedi',
        ],
      },
      {
        lga: 'Ido/Osi',
        cities: [
          'Ido',
          'Aaye',
          'Usi',
          'Ilogbo',
          'Ido',
          'Aiyetoro',
          'Ilogbo',
          'Osi Ekiti',
          'Ifaki',
          'Ipole',
          'Obaji',
          'Odo',
          'Oba-Aladesusi',
        ],
      },
      {
        lga: 'Iye',
        cities: [
          'Oye',
          'Ilafon',
          'Itapa',
          'Osin',
          'Omu Oke',
          'Omu Odo',
          'Ijelu',
          'Ode',
          'Ekiti Imesi',
          'Ekiti Aba',
          'Asua',
          'Ajegunle',
          'Aladejobi',
          'Apata-Ajo',
          'Ayelala',
          'Elewuro',
        ],
      },
      {
        lga: 'Ikole',
        cities: [
          'Ikole',
          'Agere',
          'Ajileye',
          'Apadie',
          'Ikoyi-Ile',
          'Ire',
          'Ijesa-Isu',
          'Ikole',
          'Oke-Ako',
          'Ijesha',
          'Iyemero',
          'Temidire',
          'Ikunri',
          'Ijebu-Agege',
          'Ilamo',
          'Ayebode',
          'Ikosi',
        ],
      },
      {
        lga: 'Moba',
        cities: [
          'Otun Ekiti',
          'Igogo Ekiti',
          'Aaye-Oja',
          'Osan Ekiti',
          'Iro Ekiti',
          'Irare Ekiti',
          'Isaoye Ekiti',
          'Ikosu Ekiti',
          'Epe-Ekiti',
          'Ikun Ekiti',
        ],
      },
      {
        lga: 'Gboyin',
        cities: [
          'Ode Ekiti',
          'Ode',
          'Agbado',
          'Imesi',
          'Aisegba',
          'Egbe',
          'Ijan',
          'Ilumoba',
          'Iro',
          'Aba-Baale',
          'Aba-Jibola',
          'Ugboeku',
          'Oke-Afa',
          'Olorunda',
        ],
      },
      {
        lga: 'Efon',
        cities: [
          'Efon Alaiye',
          'Oro',
          'Obake',
          'Iwaji',
          'Etisan',
          'Abete',
          'Agboro',
          'Aladura',
          'Alagba',
          'Mesan',
          'Alawaye',
          'Araromi',
          'Ido-Ajegunle',
          'Igbo-Aba',
        ],
      },
      {
        lga: 'Ise/Orun',
        cities: [
          'Ise Ekiti',
          'Erinwa',
          'Odo Ise',
          'Oraye',
          'Orun',
          'Afolu',
          'Agbe',
          'Ajebamidele',
          'Ajebamidele Ilofa',
          'Ajegunle',
          'Alabi',
          'Alagbeda',
          'Araromi',
          'Aratu',
          'Aro',
          'Arola',
        ],
      },
      {
        lga: 'Ilejemeje',
        cities: [
          'Iye',
          'Epe',
          'Ira',
          'Iro',
          'Otun Ekiti',
          'Eda Oniyo',
          'Ewu',
          'Ijesamodu',
          'Iludun',
          'Ipere',
          'Iye',
          'Obada',
          'Osan',
          'Erinmope',
          'Igogo',
          'Iye',
          'Ewu',
          'Obada Isaoye',
          'Kosu',
        ],
      },
    ],
  },
};

const cityData = {};

export { getStateLga, getLgaCity };
