const getStateLga = (state) => stateData[state];

const getLgaCity = (lga) => cityData[lga];

const stateData = {
  northcentral: {
    benue: [
      { lga: 'Agatu', cities: ['Obagaji', 'Obaji'] },
      {
        lga: 'Apa',
        cities: [
          'Ugbokpo',
          'Iga',
          'Akpete',
          'Oiji',
          'Ojope',
          'Igoro',
          'Ochekwu',
          'Edikwu',
          'Achaba',
          'Ahija',
          'Adija',
          'Amoke',
          'Akpanta',
          'Auke',
        ],
      },
      {
        lga: 'Ado',
        cities: ['Igumale'],
      },
      {
        lga: 'Buruku',
        cities: [
          'Buruku',
          'Etilo',
          'Mbaakura',
          'Binev',
          'Mbaade',
          'Mbaatirkya',
          'Mbarkyongo',
          'Mbaazager',
          'Mbarkyongo',
          'Mbatyough',
          'Mbaya',
          'Mbayaka',
          'Akpanta',
          'Shorov',
        ],
      },
      {
        lga: 'Gboko',
        cities: [
          'Gboko',
          'Igyorov',
          'Mbaa Varakaa',
          'Mbaanku',
          'Mbadam',
          'Mbakper',
        ],
      },
      {
        lga: 'Guma',
        cities: [
          'Gbajimba',
          'Mbaawa',
          'Mbabai',
          'Mbasaan',
          'Mbagwen',
          'Uyiev',
          'Daudu',
          'Torkula',
          'Kase Yough',
          'Abinsi',
          'Mbabegha',
          'Agasha',
        ],
      },
      {
        lga: 'Gwer West',
        cities: [
          'Naka',
          'Aondoana',
          'Agagbe',
          'Naji Camp',
          'Jimba',
          'Bunka',
          'Kule',
          'Yonov',
          'Mbakpa',
          'Raav',
          'Njiriv',
          'Ingohov',
          'Ikyande',
          'Enger',
        ],
      },
      {
        lga: 'Gwer East',
        cities: ['Aliade', 'Yonor', 'Ngyonov', 'Nijiriv', 'Raav', 'Mbakpa'],
      },
      {
        lga: 'Katsina-Ala',
        cities: [
          'Katsina-Ala',
          'Katsina Ota',
          'Gbor',
          'Ammatu',
          'Tor Donga',
          'Abaji',
          'Sai',
          'Harga',
          'Mbaton',
          'Gbise',
        ],
      },
      {
        lga: 'Konshisha',
        cities: [
          'Tse-Agberagba',
          'Gungul',
          'Mbavaa',
          'Aba',
          'Abagi',
          'Ko',
          'Aduu',
        ],
      },
      {
        lga: 'Kwande',
        cities: [
          'Adikpo',
          'Nanev',
          'Turan',
          'Ikurave-Ya',
          'Shangev-Ya',
          'Tse-Gum-Mbayevikyaior',
          'Ahile/Akende',
          'Ahundu',
          'Dio',
        ],
      },
      {
        lga: 'Logo',
        cities: [
          'Ugba',
          'Torov',
          'Mbaterem',
          'Ucha',
          'Gaambe',
          'Tiev',
          'Ngenev',
          'Ugondo',
          'Tongov',
          'Kpav',
          'Gambe-Va',
          'Kyutan-Tiev',
        ],
      },
      {
        lga: 'Makurdi',
        cities: [
          'Makurdi',
          'Adaka',
          'Adeke',
          'Ajam',
          'Agbadu',
          'Agbeshir',
          'Agenada',
          'Akaan',
          'Aki',
          'Akigwe',
          'Akpehe',
          'Akume',
          'Alla',
          'Anter',
        ],
      },
      {
        lga: 'Obi',
        cities: [
          'Obarike-Ito',
          'Ito',
          'Agwatashi',
          'Adudu',
          'akanga',
          'Uwokwu',
          'Igede',
        ],
      },
      {
        lga: 'Ogbadibo',
        cities: ['Otukpa', 'Ovakan', 'Owukpa'],
      },
      {
        lga: 'Oju',
        cities: [
          'Oju',
          'Uwokwu',
          'Adega',
          'Abelega',
          'Abofutu',
          'Ameka',
          'Akunda',
          'Adiko',
        ],
      },
      {
        lga: 'Okpokwu',
        cities: [
          'Okpoga',
          'Ichanna',
          'Orokam',
          'Otukpa',
          'Owukpa',
          'Okpoga',
          'Edumoga',
        ],
      },
      {
        lga: 'Ohimini',
        cities: [
          'Idekpa',
          'Onyagede',
          'Enumona',
          'Ogoli',
          'Ogande',
          'Umonomi',
          'Okpiko',
          'Iyaya',
          'Idekpa',
          'Awume',
          'Ikpoke',
          'Ogudu',
        ],
      },
      {
        lga: 'Oturkpo',
        cities: [
          'Oturkpo',
          'Ugboju Ehole',
          'Ugboju icho',
          'Ugboju otehe',
          'Adoka Icho',
          'Adoka Itaje',
          'Ewulo',
          'Okete',
          'Oturkpo East',
          'Oturkpo West',
        ],
      },
      {
        lga: 'Tarka',
        cities: [
          'Wannune',
          'Tarka',
          'Mbaajir',
          'Akaa',
          'Mbaigba',
          'Mbaayo',
          'Tongor',
          'Yandev',
          'Ipav',
          'Mbayion',
          'Mbalagh',
          'Mbatie',
          'Kusuv',
          'Utur',
          'Shorov',
          'Mbagen',
          'Mbatiav',
          'Mbatierev',
        ],
      },
      {
        lga: 'Ukum',
        cities: [
          'Sankera',
          'Borikyo',
          'Aterayange',
          'Mbatian',
          'Uvan',
          'Lumbur',
          'Mbazum',
          'Ituuluv',
          'Tsaar',
          'Mbayenge',
          'Ugbadan',
          'Kendav',
          'Azendesh',
        ],
      },
      {
        lga: 'Ushongo',
        cities: [
          'Lessel',
          'Mbagba',
          'Mbakuha',
          'Ikov',
          'Mbaikyaa',
          'Ushongo',
          'Utange',
          'Atirkyese',
          'Mbaivende',
        ],
      },
      {
        lga: 'Vandeikya',
        cities: [
          'Vandeikya',
          'Mindev',
          'Mbaka Ange',
          'Mbaduka',
          'Mbagbera',
          'Mbayongo',
          'Mbara',
          'Ute',
          'Mbava',
          'Tsambe',
        ],
      },
    ],
  },
  northeast: {
    borno: [
      {
        lga: 'Abadam',
        cities: [
          'Malumfatori',
          'Banowa',
          'Jabullam',
          'Fuguwa',
          'Arege',
          'Yau',
          'Yawa Kura',
          'Mollam Kaunari',
          'Kudokurgu',
        ],
      },
      {
        lga: 'Askira/Uba',
        cities: [
          'Askira',
          'Bagiau',
          'Chul',
          'Dum Bam',
          'Giwa Kir Koma',
          'Jimbulumu',
          'Kauthlama',
          'Njoma',
          'Uba',
          'Uwataku',
          'Yimirali',
          'Dille',
          'Gegombi',
          'Huyum',
          'Kuhi',
        ],
      },
      {
        lga: 'Bama',
        cities: [
          'Bama',
          'Kaigamari',
          'Zarawuyaku',
          'Andara',
          'Ajiri Wulba',
          'Buduwa',
          'Jere',
        ],
      },
      {
        lga: 'Bayo',
        cities: [
          'Biriyel',
          'Balbaya',
          'Fikayel',
          'Gamadadi',
          'Jara Dali',
          'Jara Gol',
          'Limanti',
          'Teli',
          'Wuyo',
          'Zara',
        ],
      },
      {
        lga: 'Biu',
        cities: [
          'Biu',
          'Zarawuyaku',
          'Waka',
          'Mandara',
          'Abdu',
          'Garwashina',
          'Tabra',
          'Burutai',
          'Dadin Kowa',
          'Dugja',
          'Garubula',
          'Gur',
          'Kenken',
          'Mandara Girau',
          'Miringa',
          'Sulumthla',
          'Yawi',
        ],
      },
      {
        lga: 'Damboa',
        cities: [
          'Damboa',
          'Ajign',
          'Azur',
          'Multe',
          'Forfor',
          'Bego',
          'Yerwa',
          'Ngurna',
          'Gumsuri',
          'Misakurbudu',
          'Kafa',
          'Mafi',
          'Mulgwai',
          'Kopchi',
          'Nguda',
          'Wuyaram',
          'Wawa',
          'Korede',
        ],
      },
      {
        lga: 'Dikwa',
        cities: [
          'Dikwa',
          'Sheffri',
          'Boboshe',
          'Dikwa',
          'Gajibo',
          'Magarta',
          'Mallam Maja',
          'Mudu',
          'Kaza',
          'Muliye',
          'Jemuri',
          'Ngudoram',
          'Sogoma',
          'Afuye',
          'Ufaye',
          'Gujile',
        ],
      },
      {
        lga: 'Gubio',
        cities: [
          'Gubio',
          'Ardimini',
          'Dabira',
          'Felo',
          'Gamowo',
          'Gazabure',
          'Kingowa',
          'Ngetra',
          'Zowo',
        ],
      },
      {
        lga: 'Guzamala',
        cities: [
          'Gwoza',
          'Ashigashia',
          'Balangaje',
          'Balazala',
          'Barawa',
          'Bokko',
          'Bulabulin',
          'Duma',
          'Falagwe',
          'Gadful',
          'Bubayawa Gudul',
          'Ngoshe Pulka',
          'Ashigashiya',
          'Bita',
          'Izge',
          'Dure',
          'Wala',
          'Warabe',
        ],
      },
      {
        lga: 'Hawul',
        cities: [
          'Azare',
          'Sakwa',
          'Kwajaffa Hang Kwaya-Bur Tanga-Rumta',
          'Marama',
          'Kidang',
          'Pama',
          'Whitambaya',
          'Puba',
          'Vidau',
          'Lokoja',
          'Hema',
          'Hawul',
          'Shaffa',
        ],
      },
      {
        lga: 'Jere',
        cities: [
          'Khaddamari',
          'Dala Lawanti',
          'Dusuman',
          'Gamboru',
          'Gomari',
          'Gongulong',
          'Jere',
          'Koshebe',
          'Lawanti',
          'Maimusari',
          'Masu',
          'Ngudda',
          'Tuba',
        ],
      },
      {
        lga: 'Kaga',
        cities: [
          'Benisheikh',
          'Afa',
          'Borgozo',
          'Dogoma',
          'Jalori',
          'Dongo',
          'Galangi',
          'Guwo',
          'Karagaru',
          'Mainok',
          'Marguba',
          'Ngamdu',
          'Shettimari',
          'Tobolo',
          'Wajiro',
          'Burgumma',
          'Wassaram',
        ],
      },
      {
        lga: 'Kala/Balge',
        cities: [
          'Rann',
          'Kalam',
          'Kulakula',
          'Kutilar',
          'Mada',
          'Moholo',
          'Masana',
          'Maleri',
          'Mokholo',
          'Sabba',
          'Sigal',
          'Tilam',
        ],
      },
      {
        lga: 'Konduga',
        cities: [
          'Konduga',
          'Lamboa',
          'Bazamri',
          'Dalori',
          'Kellumiri',
          'Konduga',
          'Malari',
          'Ngalimari',
          'Wanori',
          'Yabal',
          'Garu',
          'Auno',
          'Chabbol',
          'Wanori',
          'Dawa',
          'Kangamari',
          'Jewu',
        ],
      },
      {
        lga: 'Kukawa',
        cities: [
          'Kukawa',
          'Alagarno',
          'Baga',
          'Kanembu Adua Ajiri',
          'Alagama',
          'Bundur',
          'Dogoshi',
          'Doro',
          'Duguri',
          'Kauwa',
          'Kekeno',
          'Kukawa',
          'Moduari',
          'Barwari',
          'Yoyo',
        ],
      },
      {
        lga: 'Kwaya Kusar',
        cities: [
          'Kwaya Kusar',
          'Gondi',
          'Kusar',
          'Gusi',
          'Billa',
          'Guwal',
          'Kubuku',
          'Kurba',
          'Kwaya Kusar',
          'Peta',
          'Wada',
          'Yimrthalang',
          'Algarno',
        ],
      },
      {
        lga: 'Mafa',
        cities: [
          'Masu',
          'Mujigine',
          'Tamsu',
          'Ngamdua',
          'Anadua',
          'Kajari',
          'Loslari',
          'Mafa Nguranna',
          'Mafa',
          'Abbari',
          'Mbuta',
          'Mijigine',
          'Siguabuya',
          'Umarari',
        ],
      },
      {
        lga: 'Magumeri',
        cities: [
          'Magumeri',
          'Hoyo',
          'Magumeri',
          'Ayi',
          'Yasku',
          'Furram',
          'Borno Yesu',
          'Gaji Ganna',
          'Chin',
          'Gowa',
          'Ngubula',
          'Ngamma',
          'Kavevam',
          'Kalizoram',
        ],
      },
      {
        lga: 'Maiduguri',
        cities: [
          'Maiduguri Urban',
          'Bolori',
          'Bulablin',
          'Gamboru Liberty',
          'Gwange',
          'Shehiri',
          'Mafoni',
          'Limanti',
          'Lamisula',
          'Jabba Mari',
        ],
      },
      {
        lga: 'Marte',
        cities: [
          'Marte',
          'Ala',
          'Alla Lawanti',
          'Borsori',
          'Gumna',
          'Kulli',
          'Kirenowa',
          'Mawulli',
          'Njine',
          'Zaga',
          'Kabuluwa',
        ],
      },
      {
        lga: 'Mobbar',
        cities: [
          'Damasak',
          'Chamba',
          'Asaga',
          'Mobbar',
          'Diju',
          'Kaveto',
          'Layi',
          'Zanna Umorti',
          'Ghashagar',
        ],
      },
      {
        lga: 'Monguno',
        cities: [
          'Monguno',
          'Kumalia',
          'Damakuli',
          'Kaguram',
          'Mintar',
          'Mofio',
          'Ngurno',
          'Sure',
          'Wulo',
          'Yele',
          'Zulum',
        ],
      },
      {
        lga: 'Ngala',
        cities: [
          'Gambolu',
          'Fuye',
          'Ngala',
          'Ndufu',
          'Sagir',
          'Tunokalia',
          'Warshele',
          'Wulgo',
          'Rana',
          'Wurge',
          'Old Gamboru',
          'Logumare',
        ],
      },
      {
        lga: 'Nganzai',
        cities: [
          'Gajiram',
          'Nganzai',
          'Alarge',
          'Damaram',
          'Gadai',
          'Kuda',
          'Kurnawa',
          'Maiwa',
          'Miye',
          'Sugundure',
          'Gajiram',
          'Sabsabuwa',
        ],
      },
      {
        lga: 'Shani',
        cities: [
          'Shani',
          'GAsi',
          'Buma',
          'Bargu',
          'Lakundum',
          'Gora',
          'Gwolasho',
          'Gwashaka',
          'Kombo',
          'Kubo',
          'Kwaba',
          'Wokama',
          'Salifawa',
        ],
      },
    ],
  },
  northwest: {},
  southeast: {
    abia: [
      {
        lga: 'Aba North',
        cities: [
          'Eziama',
          'Ogbo',
          'Osusu',
          'Umuokoji',
          'Umuola-Egbule',
          'Umuola-Okpulor',
          'Uratta',
        ],
      },
      {
        lga: 'Aba South',
        cities: [
          'Abaukwu',
          'Amanfuru',
          'Ariaria',
          'Asaeme',
          'Asaokpuja',
          'Ihieorji',
          'Ndiegori',
          'Nnetu',
          'Ohabiam',
          'Umuagbai',
          'Umumb',
          'Umuosi',
        ],
      },
      {
        lga: 'Arochukwu',
        cities: [
          'Amasu',
          'Amoba',
          'Amuze',
          'Arochukwu',
          'Ibom',
          'Obinkita',
          'Oro',
          'Ujari',
        ],
      },
      {
        lga: 'Bende',
        cities: [
          'Alayi',
          'Bende',
          'Humbauzo',
          'Igbere',
          'Itumbauzo',
          'Nkpa',
          'Ozuitem',
          'Ugwueke',
          'Umu-Menyi',
          'Umuhu-Ezexhi',
          'Uzuakoli',
        ],
      },
      {
        lga: 'Ikwuano',
        cities: [
          'Ariam',
          'Ibeku',
          'Ibere',
          'Ikwuano',
          'Omuegwu',
          'Umuhu',
          'Umuokpara',
          'Usok',
        ],
      },
      {
        lga: 'Isiala-Ngwa North',
        cities: [
          'Ama-Asa',
          'Amapu-Ntigha',
          'Amasa-Ntigha',
          'Okpuala-Ngwa',
          'Ngwa Ukwu',
        ],
      },
      {
        lga: 'Isiala-Ngwa South',
        cities: [
          'Ahana',
          'Amaise',
          'Amaise-Ahoba',
          'Isiala-Nvosi',
          'Mbutu',
          'Ngwa',
          'Okporo',
          'Omoba',
          'Osokwa-Nvosi',
          'Ovu-Ngwa',
        ],
      },
      {
        lga: 'Isuikwato',
        cities: [
          'Achara-Ut',
          'Ezere',
          'Imenyi',
          'Isu-Amawu',
          'Mgbaugwu',
          'Ogudo- Asa',
          'Ohaise',
          'Umun-Nekwu',
        ],
      },
      { lga: 'Ngwa', cities: ['Ngwa'] },
      {
        lga: 'Obi Ngwa',
        cities: [
          'Abayi',
          'Ahiaba',
          'Akuma-Imo',
          'Ibeme',
          'Mgboko',
          'Mgboko-Amiri',
          'Mgboko-Otu Ngwa',
          'Ntiagha-Uzor',
          'Onuma',
        ],
      },
      {
        lga: 'Ohafia',
        cities: [
          'Ama-Asato',
          'Amangwu-Ohafia',
          'Amasa',
          'Aro-Ngwa',
          'Aso-Akwa',
          'Ebem-Ohafia',
          'Nkporo',
          'Ohofor-Ohafia',
          'Oko-Aku',
          'Oma-Ohafia',
        ],
      },
      {
        lga: 'Osisioma',
        cities: [
          'Amaitoli',
          'Amasa',
          'Aro-Ngwa',
          'Okpu-Umuobo',
          'Osisioma',
          'Oso-Okwa',
          'Umunneise',
          'Uratta',
        ],
      },
      {
        lga: 'Ugwunagbo',
        cities: [
          'Abayi',
          'Akanu',
          'Alaoji',
          'Amaokpu-Umuitiri',
          'Obuzor',
          'Osusu-Aku',
          'Ozaa-Umuebukwu',
          'Ugwunagbo',
          'Uke',
        ],
      },
      {
        lga: 'Ukwa East',
        cities: [
          'Akwete',
          'Ala-Ukwu',
          'Azumini',
          'Ibeme',
          'Ikwueke',
          'Ikwuo-Rieator',
          'Ntigha-uzo',
          'Obohia',
          'Umuigbube-Achara',
        ],
      },
      {
        lga: 'Ukwa West',
        cities: ['Asa-North', 'Obokwe', 'Oke-Ikpe', 'Ozar-Ukwu', 'Ozar-West'],
      },
      {
        lga: 'Umuahia North',
        cities: ['Ndume', 'Ohokobe', 'Ossa', 'Ugwunihara'],
      },
      {
        lga: 'Umuahia South',
        cities: [
          'Ahiaukwa',
          'Amakama',
          'Apumiri',
          'Nsirimo',
          'Ohiaocha',
          'Old Umuahia',
          'Omaegwu',
          'Ubalaka',
        ],
      },
      {
        lga: 'Umu-Nneochi',
        cities: ['Achara', 'Lomara', 'Nkwo-Agu', 'Umuelem'],
      },
    ],
    ebonyi: [
      {
        lga: 'Afikpo South',
        cities: [
          'Nguzu Edda',
          'Owutu-Edda',
          'Ebuwana-Edda',
          'Etiti-Edda',
          'Amangwu-Edda',
          'Oso-Edda',
          'Ogbu-Egbu',
        ],
      },
      {
        lga: 'Afikpo North',
        cities: ['Afikpo', 'Ohaisu', 'Itim', 'Nkpoghoro', 'Ugwuegbu', 'Amaizu'],
      },
      {
        lga: 'Onicha',
        cities: ['Isu', 'Oshiri', 'Abaomega', 'Onicha-Igbeza', 'Ukawu', 'Isu'],
      },
      {
        lga: 'Ohaozara',
        cities: [
          'Obiozara Uburu',
          'Uburu',
          'Ugwu-Langwu',
          'Ishiagu',
          'Okposi',
          'Akaeze',
        ],
      },
      {
        lga: 'Abakaliki',
        cities: ['Nkaliki', 'Abakpa', 'Amachi', 'Amagu', 'Amagu Unuhu'],
      },
      {
        lga: 'Ishielu',
        cities: [
          'Ezillo',
          'Azuinyoba',
          'Nkalaha',
          'Nkolagu',
          'Iyonu',
          'Ntezi',
          'Okpoto',
          'Agba',
          'Ezzagu',
          'Emuhu',
          'Emuhu-Ali',
          'Amazu',
          'Agge-Egde',
          'Ebeagu',
        ],
      },
      {
        lga: 'Ikwo',
        cities: [
          'Achara',
          'Ndufu-Alike',
          'Ndufu-Achara',
          'Eka-Awoke',
          'Ndiagu Achara',
          'Akpan-Wudele',
          'Igbudu',
          'Ndiagu.Amagu',
          'Ndufu-Amagu',
          'Etim-Ekpuitumo',
          'Edua-Alike',
          'Enyibichiri-Alike',
          'Agge-Egde',
          'Inyimagu',
        ],
      },
      {
        lga: 'Ezza North',
        cities: [
          'Ebiaji',
          'Amagu',
          'Amawula',
          'Achara-Ezza',
          'Amana',
          'Amazu',
          'Ameka',
          'Amuda',
          'Amuda-Ekka',
        ],
      },
      {
        lga: 'Ohaukwu',
        cities: [
          'Ezzamgbo',
          'Umuezeoka-Ogbo',
          'Umuogudu-Oshia',
          'Amoffia',
          'Ngbo',
          'Okposi-Eheku',
          'Umugudu',
          'Okposhi-Ngbo',
          'Ekwashi-Ngbo',
          'Ukwuagba-Ngbo',
          'Effium',
        ],
      },
      {
        lga: 'Ebonyi',
        cities: [
          'Ugbodo',
          'Amadi',
          'Nkoleke-Achara',
          'Izzi Unuhu',
          'Nkaleke-Achara',
          'Okpui-Tumo',
          'Edda',
          'Amagu',
          'Ishieke',
        ],
      },
      {
        lga: 'Ivo',
        cities: [
          'Isiako',
          'Ishiagu',
          'Akaeze Ukwu',
          'Amagu',
          'Amonye',
          'Ihenta',
          'Ogidi',
          'Iyioji',
          'Akaeze',
          'Ndiokoro Ukwu',
          'Ngwogwo',
          'Obinagu',
          'Okue',
          'Umobo',
          'Agbaja',
          'Anyanwuigwe',
        ],
      },
    ],
  },
  southsouth: {
    crossRiver: [
      {
        lga: 'Akpabuyo',
        cities: [
          'Ikot Nakanda',
          'Atimbo',
          'Eneyo',
          'Ikang',
          'Idundu',
          'Ikot Edem Odo',
          'Ikot Eyo',
        ],
      },
      {
        lga: 'Akamkpa',
        cities: [
          'Akamkpa',
          'Egup-Ipa',
          'Ehom',
          'Erei',
          'Iko Ekpe-Rem',
          'Ikpai',
          'Netin',
          'Ito',
          'Oban',
          'Ojuk',
          'Ubang-Hara',
          'Umon',
          'Uyanga',
        ],
      },
      {
        lga: 'Biase',
        cities: [
          'Akpet Central',
          'Abanwan',
          'Afono',
          'Edu/Elu',
          'Egbor',
          'Etana',
          'Ipene',
          'Ipine',
          'Ibini',
          'Obum',
          'Umolor',
          'Urugbam',
        ],
      },
      {
        lga: 'Abi',
        cities: [
          'Itigidi',
          'Adadama',
          'Afafanyi',
          'Igonigoni',
          'Ekureku',
          'Imabana',
          'Usumutong',
          'Ubuego',
          'Itigidi',
          'Ebom',
          'Ediba/Anong',
        ],
      },
      {
        lga: 'Ikom',
        cities: [
          'Ikom',
          'Abakpa',
          'Bisiri',
          'Bojor Achibong',
          'Obudu',
          'Oguja',
          'Okim Osabor',
          'Okuku',
        ],
      },
      {
        lga: 'Yarkur',
        cities: [
          'Ugep',
          'Abanakpai',
          'Afrekpe',
          'Ajere',
          'Assiga',
          'Biko Biko',
          'Idomi',
          'Ijiman',
          'Ijom',
          'Ikpakapit',
          'Inyima',
          'Mkpani',
          'Nkpolo',
          'Ntan',
        ],
      },
      {
        lga: 'Obubra',
        cities: [
          'Obubra',
          'Iyalla',
          'Ofat(Adum)',
          'Ofodua(Adum)',
          'Ofombo-Ngha',
          'Okom',
          'Osopong',
        ],
      },
      {
        lga: 'Boki',
        cities: [
          'Boje',
          'Abawyum',
          'Akpara-Bong',
          'Ikom Rural',
          'Nde',
          'Nte',
          'Ofutop',
          'Osokom',
          'Etung',
        ],
      },
      {
        lga: 'Ogoja',
        cities: ['Ogoja', 'Ekajuk', 'Mbube', 'Nkum Iborr', 'Nkum Irede'],
      },
      {
        lga: 'Yala',
        cities: [
          'Okpoma',
          'Yahe',
          'Ugaga',
          'Ijegu',
          'Oloko',
          'Imaje',
          'Oke',
          'Echumoga',
          'Woda',
          'Ebo',
          'Igede Edii',
          'Itekpa',
          'Maa',
          'Wonye',
          'Uchu',
          'Osina',
        ],
      },
      {
        lga: 'Obanliku',
        cities: [
          'Sankwala',
          'Basang',
          'Bebi',
          'Becheve',
          'Bendi',
          'Bishiri',
          'Busi',
          'Bisu',
          'Utanga',
        ],
      },
      {
        lga: 'Obudu',
        cities: [
          'Obudu',
          'Alege',
          'Becheve',
          'Bettee',
          'Oban-Liku',
          'Okpe',
          'South Oban-Liku',
          'Ugang',
          'Unpe',
          'Utanga',
          'Utygwang',
        ],
      },
      {
        lga: 'Calabar South',
        cities: ['Anantigha'],
      },
      {
        lga: 'Etung',
        cities: [
          'Effraya',
          'Abia',
          'Abijang',
          'Agbokim',
          'Ajassor',
          'Bendeghe',
          'Ekiem',
          'Effraya',
          'Etomi',
          'Itaka',
          'Mkpot/Ayuk Aba',
          'Nsofang',
        ],
      },
      {
        lga: 'Bekwara',
        cities: [
          'Abuochiche',
          'Afrike',
          'Yala',
          'Ejajuk',
          'Gabu',
          'Gakem',
          'Mbube',
          'Nkum',
          'Ukele',
          'Ogoja Urban',
          'Western Yala Ya',
          'Yache',
        ],
      },
      {
        lga: 'Bakassi',
        cities: [
          'Ikang',
          'Abana',
          'Akpankanya',
          'Akwa',
          'Amoto',
          'Ambai Ekpa',
          'Archibong',
          'Atai',
          'Ema',
          'Efut Iwang',
          'Ekpot Abia',
          'Odiong',
        ],
      },
    ],
    delta: [
      {
        lga: 'Oshimili',
        cities: [
          'Asaba',
          'Abraka',
          'Burutu',
          'Koko',
          'Oghara',
          'Okuokoko',
          'Ovwian',
          'Sapele',
          'Warri',
          'Agbor',
          'Effurun',
          'Kwale',
          'Ogwashi Ukwu',
          'Oleh',
          'Ozoro',
          'Ughelli',
        ],
      },
      {
        lga: 'Aniocha South',
        cities: [
          'Asaba',
          'Abraka',
          'Burutu',
          'koko',
          'Oghara',
          'Okuokoko',
          'Ovwian',
          'Sapele',
          'Warri',
          'Agbo',
          'Effurun',
          'Kwale',
          'Ogwashi Ukwu',
          'Oleh',
          'Ozoro',
          'Ughelli',
        ],
      },
      {
        lga: 'Ika South',
        cities: [
          'Asaba',
          'Abraka',
          'Burutu',
          'koko',
          'Oghara',
          'Okuokoko',
          'Ovwian',
          'Sapele',
          'Warri',
          'Agbo',
          'Effurun',
          'Kwale',
          'Ogwashi Ukwu',
          'Oleh',
          'Ozoro',
          'Ughelli',
        ],
      },
      {
        lga: 'Ika North-East',
        cities: [
          'Asaba',
          'Abraka',
          'Burutu',
          'koko',
          'Oghara',
          'Okuokoko',
          'Ovwian',
          'Sapele',
          'Warri',
          'Agbo',
          'Effurun',
          'Kwale',
          'Ogwashi Ukwu',
          'Oleh',
          'Ozoro',
          'Ughelli',
        ],
      },
      {
        lga: 'Ndokwa West',
        cities: [
          'Asaba',
          'Abraka',
          'Burutu',
          'koko',
          'Oghara',
          'Okuokoko',
          'Ovwian',
          'Sapele',
          'Warri',
          'Agbo',
          'Effurun',
          'Kwale',
          'Ogwashi Ukwu',
          'Oleh',
          'Ozoro',
          'Ughelli',
        ],
      },
      {
        lga: 'Ndokwa East',
        cities: [
          'Asaba',
          'Abraka',
          'Burutu',
          'koko',
          'Oghara',
          'Okuokoko',
          'Ovwian',
          'Sapele',
          'Warri',
          'Agbo',
          'Effurun',
          'Kwale',
          'Ogwashi Ukwu',
          'Oleh',
          'Ozoro',
          'Ughelli',
        ],
      },
      {
        lga: 'Isoko South',
        cities: [
          'Asaba',
          'Abraka',
          'Burutu',
          'koko',
          'Oghara',
          'Okuokoko',
          'Ovwian',
          'Sapele',
          'Warri',
          'Agbo',
          'Effurun',
          'Kwale',
          'Ogwashi Ukwu',
          'Oleh',
          'Ozoro',
          'Ughelli',
        ],
      },
      {
        lga: 'Isoko North',
        cities: [
          'Asaba',
          'Abraka',
          'Burutu',
          'koko',
          'Oghara',
          'Okuokoko',
          'Ovwian',
          'Sapele',
          'Warri',
          'Agbo',
          'Effurun',
          'Kwale',
          'Ogwashi Ukwu',
          'Oleh',
          'Ozoro',
          'Ughelli',
        ],
      },
      {
        lga: 'Bomadi',
        cities: [
          'Asaba',
          'Abraka',
          'Burutu',
          'koko',
          'Oghara',
          'Okuokoko',
          'Ovwian',
          'Sapele',
          'Warri',
          'Agbo',
          'Effurun',
          'Kwale',
          'Ogwashi Ukwu',
          'Oleh',
          'Ozoro',
          'Ughelli',
        ],
      },
      {
        lga: 'Burutu',
        cities: [
          'Asaba',
          'Abraka',
          'Burutu',
          'koko',
          'Oghara',
          'Okuokoko',
          'Ovwian',
          'Sapele',
          'Warri',
          'Agbo',
          'Effurun',
          'Kwale',
          'Ogwashi Ukwu',
          'Oleh',
          'Ozoro',
          'Ughelli',
        ],
      },
      {
        lga: 'Ughelli South',
        cities: [
          'Asaba',
          'Abraka',
          'Burutu',
          'koko',
          'Oghara',
          'Okuokoko',
          'Ovwian',
          'Sapele',
          'Warri',
          'Agbo',
          'Effurun',
          'Kwale',
          'Ogwashi Ukwu',
          'Oleh',
          'Ozoro',
          'Ughelli',
        ],
      },
      {
        lga: 'Ughelli North',
        cities: [
          'Asaba',
          'Abraka',
          'Burutu',
          'koko',
          'Oghara',
          'Okuokoko',
          'Ovwian',
          'Sapele',
          'Warri',
          'Agbo',
          'Effurun',
          'Kwale',
          'Ogwashi Ukwu',
          'Oleh',
          'Ozoro',
          'Ughelli',
        ],
      },
      {
        lga: 'Ethiope West',
        cities: [
          'Asaba',
          'Abraka',
          'Burutu',
          'koko',
          'Oghara',
          'Okuokoko',
          'Ovwian',
          'Sapele',
          'Warri',
          'Agbo',
          'Effurun',
          'Kwale',
          'Ogwashi Ukwu',
          'Oleh',
          'Ozoro',
          'Ughelli',
        ],
      },
      {
        lga: 'Ethiope East',
        cities: [
          'Asaba',
          'Abraka',
          'Burutu',
          'koko',
          'Oghara',
          'Okuokoko',
          'Ovwian',
          'Sapele',
          'Warri',
          'Agbo',
          'Effurun',
          'Kwale',
          'Ogwashi Ukwu',
          'Oleh',
          'Ozoro',
          'Ughelli',
        ],
      },
      {
        lga: 'Sapele',
        cities: [
          'Asaba',
          'Abraka',
          'Burutu',
          'koko',
          'Oghara',
          'Okuokoko',
          'Ovwian',
          'Sapele',
          'Warri',
          'Agbo',
          'Effurun',
          'Kwale',
          'Ogwashi Ukwu',
          'Oleh',
          'Ozoro',
          'Ughelli',
        ],
      },
      {
        lga: 'Okpe',
        cities: [
          'Asaba',
          'Abraka',
          'Burutu',
          'koko',
          'Oghara',
          'Okuokoko',
          'Ovwian',
          'Sapele',
          'Warri',
          'Agbo',
          'Effurun',
          'Kwale',
          'Ogwashi Ukwu',
          'Oleh',
          'Ozoro',
          'Ughelli',
        ],
      },
      {
        lga: 'Warri North',
        cities: [
          'Asaba',
          'Abraka',
          'Burutu',
          'koko',
          'Oghara',
          'Okuokoko',
          'Ovwian',
          'Sapele',
          'Warri',
          'Agbo',
          'Effurun',
          'Kwale',
          'Ogwashi Ukwu',
          'Oleh',
          'Ozoro',
          'Ughelli',
        ],
      },
      {
        lga: 'Warri South',
        cities: [
          'Asaba',
          'Abraka',
          'Burutu',
          'koko',
          'Oghara',
          'Okuokoko',
          'Ovwian',
          'Sapele',
          'Warri',
          'Agbo',
          'Effurun',
          'Kwale',
          'Ogwashi Ukwu',
          'Oleh',
          'Ozoro',
          'Ughelli',
        ],
      },
      {
        lga: 'Uvwie',
        cities: [
          'Asaba',
          'Abraka',
          'Burutu',
          'koko',
          'Oghara',
          'Okuokoko',
          'Ovwian',
          'Sapele',
          'Warri',
          'Agbo',
          'Effurun',
          'Kwale',
          'Ogwashi Ukwu',
          'Oleh',
          'Ozoro',
          'Ughelli',
        ],
      },
      {
        lga: 'Udu',
        cities: [
          'Asaba',
          'Abraka',
          'Burutu',
          'koko',
          'Oghara',
          'Okuokoko',
          'Ovwian',
          'Sapele',
          'Warri',
          'Agbo',
          'Effurun',
          'Kwale',
          'Ogwashi Ukwu',
          'Oleh',
          'Ozoro',
          'Ughelli',
        ],
      },
      {
        lga: 'Warri Central',
        cities: [
          'Asaba',
          'Abraka',
          'Burutu',
          'koko',
          'Oghara',
          'Okuokoko',
          'Ovwian',
          'Sapele',
          'Warri',
          'Agbo',
          'Effurun',
          'Kwale',
          'Ogwashi Ukwu',
          'Oleh',
          'Ozoro',
          'Ughelli',
        ],
      },
      {
        lga: 'Ukwani',
        cities: [
          'Asaba',
          'Abraka',
          'Burutu',
          'koko',
          'Oghara',
          'Okuokoko',
          'Ovwian',
          'Sapele',
          'Warri',
          'Agbo',
          'Effurun',
          'Kwale',
          'Ogwashi Ukwu',
          'Oleh',
          'Ozoro',
          'Ughelli',
        ],
      },
      {
        lga: 'Oshimili North',
        cities: [
          'Asaba',
          'Abraka',
          'Burutu',
          'koko',
          'Oghara',
          'Okuokoko',
          'Ovwian',
          'Sapele',
          'Warri',
          'Agbo',
          'Effurun',
          'Kwale',
          'Ogwashi Ukwu',
          'Oleh',
          'Ozoro',
          'Ughelli',
        ],
      },
      {
        lga: 'Patani',
        cities: [
          'Asaba',
          'Abraka',
          'Burutu',
          'koko',
          'Oghara',
          'Okuokoko',
          'Ovwian',
          'Sapele',
          'Warri',
          'Agbo',
          'Effurun',
          'Kwale',
          'Ogwashi Ukwu',
          'Oleh',
          'Ozoro',
          'Ughelli',
        ],
      },
    ],
    edo: [
      {
        lga: 'Esan North-East',
        cities: ['Uromi', 'Edo Esan', 'Uzea'],
      },
      {
        lga: 'Esan West',
        cities: [
          'Ekpoma',
          'Eghoro',
          'Idio',
          'Naoka',
          'Ogwa',
          'Ujiogba',
          'Ukhun',
          'Urohi',
        ],
      },
      {
        lga: 'Akoko-Edo',
        cities: [
          'Igarra',
          'Akoko',
          'Ikpeshi-Egbegbere',
          'Atje',
          'Kakumo-Anyantan',
        ],
      },
      {
        lga: 'Egor',
        cities: [
          'Uselu',
          'Agidigbi',
          'Egor',
          'Environ Camp',
          'Iguediayi',
          'Iguikpe',
          'Oghedaivbiobaa',
          'Oghokhegbo',
          'Oviasuyi Camp',
          'gboko',
          'Ugbi',
        ],
      },
      {
        lga: 'Ikpoba',
        cities: [
          'Idogbo',
          'Aduwawa',
          'Agedo',
          'Ekiuwa',
          'Evbumufi',
          'Evbuomodu',
          'Ighekpe',
          'Iguehana',
          'Ogbeson',
          'Ohovbe',
          'Otenes Camp',
          'Urora',
          'Ute Okha',
          'Ajoki Akpes Camp',
          'Avbiama',
        ],
      },
      {
        lga: 'Esan Central',
        cities: [
          'Irrua',
          'Ewu',
          'Opoji',
          'Ugbegun',
          'Igueben',
          'Ebelle',
          'Ewossa',
        ],
      },
      {
        lga: 'Etsako Central',
        cities: ['Fugar', 'Ekperi', 'Fugar-Avianwu', 'Okpekpe', 'Okpella'],
      },
      {
        lga: 'Igueben',
        cities: ['Igueben', 'Amahor', 'Ekpon', 'Ugun Urban'],
      },
      {
        lga: 'Oredo',
        cities: [
          'Benin',
          'Gra',
          'Etete',
          'Ibiwe',
          'Iwegie',
          'Ugbague',
          'Ihogbe',
          'Isekhere',
          'Oreoghene',
          'Ibiwe',
          'Ikpema',
          'Eguadase',
          'New Binin',
          'Ogbe',
          'Ogbelaka',
        ],
      },
      {
        lga: 'Ovia South-West',
        cities: [
          'Iguoba-Zuwa',
          'Ofunama',
          'Ora',
          'Siluko',
          'Udo',
          'Ugbogue',
          'Umaza',
          'Usen',
        ],
      },
      {
        lga: 'Ovia North-West',
        cities: [
          'Okada',
          'Adolor',
          'Iguoshodin',
          'Isiuwa',
          'Kokhuo',
          'Oduna',
          'Ofunm-Wengbe',
          'Oghede',
          'Oluku',
          'Uhiere',
          'Utoka',
        ],
      },
      {
        lga: 'Orhionwon',
        cities: [
          'Abudu',
          'Aibiokunla',
          'Igbanke',
          'Oloten',
          'Ugboko',
          'Ugu',
          'Urho-Nigbe',
        ],
      },
      {
        lga: 'Uhunmwonde',
        cities: [
          'Ehor',
          'Egbede',
          'Igieduma',
          'Isi North',
          'Isi South',
          'Uhi',
          'Umagbae',
        ],
      },
      {
        lga: 'Etsako East',
        cities: [
          'Agenebode',
          'Agiere',
          'Anumeji',
          'Avhiodor',
          'Bode-Waterside',
          'Dapapa',
          'Edegbe',
          'Egori-Nauge',
        ],
      },
      {
        lga: 'Esan South-East',
        cities: [
          'Ubiaja',
          'Emu',
          'Equare-Ewatto',
          'Ewohimi',
          'Ilushi',
          'Inyenlen',
          'Ohordua',
          'Okhu-Essan',
          'Onog-Holo',
          'Oria',
        ],
      },
    ],
  },
  southwest: {
    ekiti: [
      {
        lga: 'Ado',
        cities: [
          'Ado Ekiti',
          'Ago Araromi',
          'Ajebamidele',
          'Amirin',
          'Aso Ayegbule',
          'Ategbedo',
          'Ernfun',
          'Igim Okogo',
          'Igirigiri',
          'Ika',
          'Ikewo',
          'ilokun',
          'Iranse',
        ],
      },
      {
        lga: 'Ekiti-East',
        cities: [
          'Omuo-Ekiti',
          'Ikun',
          'Araromi',
          'Eda',
          'Ile',
          'Isinbode',
          'Eremiji',
          'Igbole',
          'Suru',
          'Omuo Ekiti',
          'Ilasa',
          'Isinbode',
          'Oda-do',
        ],
      },
      {
        lga: 'Ekiti-West',
        cities: [
          'Aramoko',
          'Ido Ajinare',
          'Ikogosi',
          'Ipole',
          'Iloro',
          'Aramoko',
          'Erinijiyan',
          'Okemesi',
          'Isokowa',
          'Egede',
          'Orokuta',
          'Osemo',
          'Kajola',
        ],
      },
      {
        lga: 'Emure/Ise/Orun',
        cities: [
          'Emure',
          'Oke Emure',
          'Odo Emure',
          'Ideimudu',
          'Ogbontioro',
          'Sasere',
          'Owode',
          'Owosi',
          'Igboso',
          'Ilu',
          'Oge Oke',
          'Seri',
          'Oke Sett',
          'Omaje Opticum',
          'Ose',
          'Owos',
          'Agbanimu',
        ],
      },
      {
        lga: 'Ekiti South-West',
        cities: [
          'Ilawe',
          'Igbara Odo',
          'Ilawe I',
          'Ilawe II',
          'Ilawe III',
          'Ilawe IV',
          'Ilawe V',
          'Igbara Odo I',
          'Igbara Odo II',
        ],
      },
      {
        lga: 'Ikere',
        cities: [
          'Okejegbende',
          'Oniroba',
          'Okeruku',
          'Ugele/Aroku',
          'Aso-Osolo',
          'Atoba',
          'Aba Igbira',
          'Ugbo-Oje',
          'Ijao',
          'Odese',
          'Ogbonjana',
          'Oke-Osun',
          'Oyo',
          'Are Araromi',
          'Ugbo-Uro',
        ],
      },
      {
        lga: 'Irepodun',
        cities: [
          'Igede-Ekiti',
          'Iyin-Ekiti',
          'Igbemo-Ekiti',
          'Awo-Ekiti Afao',
          'Are',
          'Awo',
          'Igbemo',
          'Iropora',
          'Esure',
          'Eyio',
          'Iworoko',
        ],
      },
      {
        lga: 'Ijero',
        cities: [
          'Ijero',
          'Ekamarun',
          'Ikoro',
          'iloro',
          'Ijunrin',
          'Ipoti',
          'Odo',
          'Owa',
          'Idao',
          'Ilukuno',
          'Iroko',
          'Temidire',
          'Abedi',
        ],
      },
      {
        lga: 'Ido/Osi',
        cities: [
          'Ido',
          'Aaye',
          'Usi',
          'Ilogbo',
          'Ido',
          'Aiyetoro',
          'Ilogbo',
          'Osi Ekiti',
          'Ifaki',
          'Ipole',
          'Obaji',
          'Odo',
          'Oba-Aladesusi',
        ],
      },
      {
        lga: 'Iye',
        cities: [
          'Oye',
          'Ilafon',
          'Itapa',
          'Osin',
          'Omu Oke',
          'Omu Odo',
          'Ijelu',
          'Ode',
          'Ekiti Imesi',
          'Ekiti Aba',
          'Asua',
          'Ajegunle',
          'Aladejobi',
          'Apata-Ajo',
          'Ayelala',
          'Elewuro',
        ],
      },
      {
        lga: 'Ikole',
        cities: [
          'Ikole',
          'Agere',
          'Ajileye',
          'Apadie',
          'Ikoyi-Ile',
          'Ire',
          'Ijesa-Isu',
          'Ikole',
          'Oke-Ako',
          'Ijesha',
          'Iyemero',
          'Temidire',
          'Ikunri',
          'Ijebu-Agege',
          'Ilamo',
          'Ayebode',
          'Ikosi',
        ],
      },
      {
        lga: 'Moba',
        cities: [
          'Otun Ekiti',
          'Igogo Ekiti',
          'Aaye-Oja',
          'Osan Ekiti',
          'Iro Ekiti',
          'Irare Ekiti',
          'Isaoye Ekiti',
          'Ikosu Ekiti',
          'Epe-Ekiti',
          'Ikun Ekiti',
        ],
      },
      {
        lga: 'Gboyin',
        cities: [
          'Ode Ekiti',
          'Ode',
          'Agbado',
          'Imesi',
          'Aisegba',
          'Egbe',
          'Ijan',
          'Ilumoba',
          'Iro',
          'Aba-Baale',
          'Aba-Jibola',
          'Ugboeku',
          'Oke-Afa',
          'Olorunda',
        ],
      },
      {
        lga: 'Efon',
        cities: [
          'Efon Alaiye',
          'Oro',
          'Obake',
          'Iwaji',
          'Etisan',
          'Abete',
          'Agboro',
          'Aladura',
          'Alagba',
          'Mesan',
          'Alawaye',
          'Araromi',
          'Ido-Ajegunle',
          'Igbo-Aba',
        ],
      },
      {
        lga: 'Ise/Orun',
        cities: [
          'Ise Ekiti',
          'Erinwa',
          'Odo Ise',
          'Oraye',
          'Orun',
          'Afolu',
          'Agbe',
          'Ajebamidele',
          'Ajebamidele Ilofa',
          'Ajegunle',
          'Alabi',
          'Alagbeda',
          'Araromi',
          'Aratu',
          'Aro',
          'Arola',
        ],
      },
      {
        lga: 'Ilejemeje',
        cities: [
          'Iye',
          'Epe',
          'Ira',
          'Iro',
          'Otun Ekiti',
          'Eda Oniyo',
          'Ewu',
          'Ijesamodu',
          'Iludun',
          'Ipere',
          'Iye',
          'Obada',
          'Osan',
          'Erinmope',
          'Igogo',
          'Iye',
          'Ewu',
          'Obada Isaoye',
          'Kosu',
        ],
      },
    ],
  },
};

const cityData = {};

export { getStateLga, getLgaCity };
